image: ubuntu:19.04

notf-tests:
  stage: build
  variables:
    CCACHE_COMPILERCHECK: "content"
  before_script:
    - apt update && apt -y install build-essential ninja-build cmake lcov uuid-dev freeglut3-dev libxrandr-dev libxcursor-dev libxinerama-dev libxi-dev libgles2-mesa-dev
    - NOTF_BASEDIR="$PWD"
    - export PATH="/usr/lib/ccache:$PATH"
    - export CCACHE_BASEDIR="$PWD" CCACHE_DIR="$PWD/ccache"
    - ccache --zero-stats --show-stats || true
  script:
    - mkdir -p ./build/ci/ && cd ./build/ci/
    - cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug $NOTF_BASEDIR
    - ninja -v
    - ./tests/notf-tests --durations yes exclude:[slow] exclude:[app]
    - lcov --capture --directory ./src/CMakeFiles/notf-core.dir/ --output-file src.cov
    - lcov --capture --directory ./tests/CMakeFiles/notf-tests.dir/ --output-file test.cov
    - lcov --add-tracefile src.cov --add-tracefile test.cov --output-file coverage.info
    - lcov --remove coverage.info "/usr/*" --output-file coverage.info
    - lcov --remove coverage.info "$NOTF_BASEDIR/thirdparty/*" --output-file coverage.info
    - lcov --remove coverage.info "$NOTF_BASEDIR/tests/*" --output-file coverage.info
    - genhtml ./coverage.info --output-directory coverage --title "notf test coverage" --prefix $NOTF_BASEDIR
  after_script:
    - export CCACHE_DIR="$PWD/ccache"
    - ccache --show-stats
  cache:
    key: ${CI_JOB_NAME}
    paths:
      - ccache
  artifacts:
    paths:
      - build/ci/coverage/

pages:
  stage: deploy
  dependencies:
    - notf-tests
  script:
    - mv build/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
