import unittest
from typing import List, Optional

from pynotf.data import Bonsai


########################################################################################################################
# TEST CASE
########################################################################################################################


class TestCase(unittest.TestCase):

    def _check_bonsai(self, names: List[str]):
        """
        Testing a Bonsai is straightforward.
        Generate one, then see if all indices match.
        """
        bonsai: Bonsai = Bonsai(names)
        for index, name in enumerate(names):
            self.assertEqual(bonsai[name], index)

    def test_generic(self):
        """
        A short list of names I would expect to be stored in a Bonsai.
        """
        self._check_bonsai([
            'xform',  # 0
            'layout_xform',  # 1
            'claim',  # 2
            'opacity',  # 3
            'period',  # 4
            'progress',  # 5
            'amplitude',  # 6
            'something else',  # 7
        ])

    def test_no_names(self):
        """
        What it says in the function name.
        """
        self._check_bonsai([])
        self.assertIsNone(Bonsai([]).get('anything'))

    def test_empty_name(self):
        """
        What happens if a name is empty from the start.
        """
        bonsai: Bonsai = Bonsai(['a', '', 'b'])
        self.assertEqual(bonsai[''], 1)

    def test_not_unique(self):
        """
        If you construct a Bonsai with duplicate names.
        """
        with self.assertRaises(ValueError):
            Bonsai(['a', 'a', 'b'])

    def test_not_found(self):
        """
        Generates a Bonsai and tries to find a name that is not part of it.
        """
        bonsai: Bonsai = Bonsai(['This', 'is', 'a', 'Bonsai'])
        with self.assertRaises(KeyError):
            _ = bonsai['ThisIsNoInTheBonsai']
        self.assertIsNone(bonsai.get('A'))
        self.assertIsNone(bonsai.get('iS'))
        self.assertIsNone(bonsai.get('z'))

    def test_wikipedia_trie(self):
        """
        See https://en.wikipedia.org/wiki/Trie
        """
        self._check_bonsai([
            'a',  # 0
            'to',  # 1
            'tea',  # 2
            'ted',  # 3
            'ten',  # 4
            'i',  # 5
            'in',  # 6
            'inn',  # 7
        ])

    def test_long(self):
        """
        When absolute offsets were stored, this Bonsai had an offset > 255, but now it works fine.
        """
        self._check_bonsai([
            'xform',
            'layout_xform',
            'claim',
            'opacity',
            'period',
            'reverse_opacity',
            'state',
            'progress',
            'phase',
            'seed',
            'width',
            'height',
            'score',
            'amplitude',
            't',
            'i',
            'value',
            'id',
            'parent_id',
            'strength',
            'power_level',
            'child_count',
            'data_offset'
            'color_r',
            'color_g',
            'color_b',
            'color_space',
            'is_critical',
            'is_reversible',
        ])

    def test_name_too_long(self):
        """
        Bonsais can not store names that are larger than 255 characters
        """
        with self.assertRaises(ValueError):
            _ = Bonsai([  # 4x64 = 256 characters long
                'LoremipsumdolorsitametconsecteturadipiscingelitDonecelitnuncsoll'
                'icitudinornarehesndreriteupellentesqueiddiamIntegerapulvinarleoP'
                'ellentesqueacefficiturloremAeneansollicitudinpharetraornareNulla'
                'auctordapibuslectussedmollisFuscenecsemeuismodelementumexetposes'
            ])

    def test_offset_too_large(self):
        """
        Offsets within a Bonsai can not be larger than 255.
        """
        with self.assertRaises(ValueError):
            _ = Bonsai([
                'A',
                'LoremipsumdolorsitametconsecteturadipiscingelitDonecelitnuncsoll'
                'icitudinornarehesndreriteupellentesqueiddiamIntegerapulvinarleoP'
                'ellentesqueacefficiturloremAeneansollicitudinpharetraornareNulla'
                'auctordapibuslectussedmollisFuscenecsemeuismodelementumexetpos',
                'z'
            ])

    def test_regressions(self):
        """
        Tests generated by Hypothesis that failed at some point.
        """
        self._check_bonsai(['0', '00'])
        self._check_bonsai(['0', '0/'])


########################################################################################################################
# TEST CASE
########################################################################################################################

if __name__ == "__main__":
    """
    Run this file itself to run tests generated by Hypothesis.
    It should simply return 0, but if it _does_ fail, add the failure condition to the list of regression tests and fix
    the bug.
    """

    from hypothesis import given
    from hypothesis.strategies import composite, lists, text


    @composite
    def unique_strings(draw):
        return draw(lists(text(), unique=True))


    @given(unique_strings())
    def test_bonsai(names: List[str]):
        bonsai: Bonsai = Bonsai(names)
        for index, name in enumerate(names):
            result: Optional[int] = bonsai[name]
            if result != index:
                raise ValueError(f'"{name}" -> {result}, but expected {index}')


    test_bonsai()
