# Import all OpenGL stuff into a common namespace and remove the `GL_` and `gl` prefixes.
# Re-create at will by running the following code:
#
#     from OpenGL import GLES3
#     print('from OpenGL import GLES3')
#     names = {}
#     for name in dir(GLES3):
#         if name.startswith('__'):
#             continue
#         elif name.startswith('GL_'):
#             names[name[3:]] = name
#         elif name.startswith('GL'):
#             names[name[2:]] = name
#         elif name.startswith('gl'):
#             names[name[2].lower() + name[3:]] = name
#         else:
#             names[name] = name
#     print('__all__ = ["{}"]'.format('", "'.join(name for name in names)))
#     for new_name, gl_name in names.items():
#         print(f'{new_name} = GLES3.{gl_name}')

from OpenGL import GLES3

__all__ = ["ARRAY_TYPE_TO_CONSTANT", "Constant", "DEBUGPROC", "DEBUGPROCAMD", "DEBUGPROCARB", "DEBUGPROCKHR",
           "ACTIVE_ATOMIC_COUNTER_BUFFERS", "ACTIVE_ATTRIBUTES", "ACTIVE_ATTRIBUTE_MAX_LENGTH", "ACTIVE_PROGRAM",
           "ACTIVE_RESOURCES", "ACTIVE_TEXTURE", "ACTIVE_UNIFORMS", "ACTIVE_UNIFORM_BLOCKS",
           "ACTIVE_UNIFORM_BLOCK_MAX_NAME_LENGTH", "ACTIVE_UNIFORM_MAX_LENGTH", "ACTIVE_VARIABLES",
           "ALIASED_LINE_WIDTH_RANGE", "ALIASED_POINT_SIZE_RANGE", "ALL_BARRIER_BITS", "ALL_SHADER_BITS", "ALPHA",
           "ALPHA_BITS", "ALREADY_SIGNALED", "ALWAYS", "ANY_SAMPLES_PASSED", "ANY_SAMPLES_PASSED_CONSERVATIVE",
           "ARRAY_BUFFER", "ARRAY_BUFFER_BINDING", "ARRAY_SIZE", "ARRAY_STRIDE", "ATOMIC_COUNTER_BARRIER_BIT",
           "ATOMIC_COUNTER_BUFFER", "ATOMIC_COUNTER_BUFFER_BINDING", "ATOMIC_COUNTER_BUFFER_INDEX",
           "ATOMIC_COUNTER_BUFFER_SIZE", "ATOMIC_COUNTER_BUFFER_START", "ATTACHED_SHADERS", "BACK", "BLEND",
           "BLEND_COLOR", "BLEND_DST_ALPHA", "BLEND_DST_RGB", "BLEND_EQUATION", "BLEND_EQUATION_ALPHA",
           "BLEND_EQUATION_RGB", "BLEND_SRC_ALPHA", "BLEND_SRC_RGB", "BLOCK_INDEX", "BLUE", "BLUE_BITS", "BOOL",
           "BOOL_VEC2", "BOOL_VEC3", "BOOL_VEC4", "BUFFER_ACCESS_FLAGS", "BUFFER_BINDING", "BUFFER_DATA_SIZE",
           "BUFFER_MAPPED", "BUFFER_MAP_LENGTH", "BUFFER_MAP_OFFSET", "BUFFER_MAP_POINTER", "BUFFER_SIZE",
           "BUFFER_UPDATE_BARRIER_BIT", "BUFFER_USAGE", "BUFFER_VARIABLE", "BYTE", "CCW", "CHAR", "CLAMP_TO_EDGE",
           "COLOR", "COLOR_ATTACHMENT0", "COLOR_ATTACHMENT1", "COLOR_ATTACHMENT10", "COLOR_ATTACHMENT11",
           "COLOR_ATTACHMENT12", "COLOR_ATTACHMENT13", "COLOR_ATTACHMENT14", "COLOR_ATTACHMENT15", "COLOR_ATTACHMENT16",
           "COLOR_ATTACHMENT17", "COLOR_ATTACHMENT18", "COLOR_ATTACHMENT19", "COLOR_ATTACHMENT2", "COLOR_ATTACHMENT20",
           "COLOR_ATTACHMENT21", "COLOR_ATTACHMENT22", "COLOR_ATTACHMENT23", "COLOR_ATTACHMENT24", "COLOR_ATTACHMENT25",
           "COLOR_ATTACHMENT26", "COLOR_ATTACHMENT27", "COLOR_ATTACHMENT28", "COLOR_ATTACHMENT29", "COLOR_ATTACHMENT3",
           "COLOR_ATTACHMENT30", "COLOR_ATTACHMENT31", "COLOR_ATTACHMENT4", "COLOR_ATTACHMENT5", "COLOR_ATTACHMENT6",
           "COLOR_ATTACHMENT7", "COLOR_ATTACHMENT8", "COLOR_ATTACHMENT9", "COLOR_BUFFER_BIT", "COLOR_CLEAR_VALUE",
           "COLOR_WRITEMASK", "COMMAND_BARRIER_BIT", "COMPARE_REF_TO_TEXTURE", "COMPILE_STATUS", "COMPRESSED_R11_EAC",
           "COMPRESSED_RG11_EAC", "COMPRESSED_RGB8_ETC2", "COMPRESSED_RGB8_PUNCHTHROUGH_ALPHA1_ETC2",
           "COMPRESSED_RGBA8_ETC2_EAC", "COMPRESSED_SIGNED_R11_EAC", "COMPRESSED_SIGNED_RG11_EAC",
           "COMPRESSED_SRGB8_ALPHA8_ETC2_EAC", "COMPRESSED_SRGB8_ETC2", "COMPRESSED_SRGB8_PUNCHTHROUGH_ALPHA1_ETC2",
           "COMPRESSED_TEXTURE_FORMATS", "COMPUTE_SHADER", "COMPUTE_SHADER_BIT", "COMPUTE_WORK_GROUP_SIZE",
           "CONDITION_SATISFIED", "CONSTANT_ALPHA", "CONSTANT_COLOR", "COPY_READ_BUFFER", "COPY_READ_BUFFER_BINDING",
           "COPY_WRITE_BUFFER", "COPY_WRITE_BUFFER_BINDING", "CULL_FACE", "CULL_FACE_MODE", "CURRENT_PROGRAM",
           "CURRENT_QUERY", "CURRENT_VERTEX_ATTRIB", "CW", "DECR", "DECR_WRAP", "DELETE_STATUS", "DEPTH",
           "DEPTH24_STENCIL8", "DEPTH32F_STENCIL8", "DEPTH_ATTACHMENT", "DEPTH_BITS", "DEPTH_BUFFER_BIT",
           "DEPTH_CLEAR_VALUE", "DEPTH_COMPONENT", "DEPTH_COMPONENT16", "DEPTH_COMPONENT24", "DEPTH_COMPONENT32F",
           "DEPTH_FUNC", "DEPTH_RANGE", "DEPTH_STENCIL", "DEPTH_STENCIL_ATTACHMENT", "DEPTH_STENCIL_TEXTURE_MODE",
           "DEPTH_TEST", "DEPTH_WRITEMASK", "DISPATCH_INDIRECT_BUFFER", "DISPATCH_INDIRECT_BUFFER_BINDING", "DITHER",
           "DONT_CARE", "DOUBLE", "DRAW_BUFFER0", "DRAW_BUFFER1", "DRAW_BUFFER10", "DRAW_BUFFER11", "DRAW_BUFFER12",
           "DRAW_BUFFER13", "DRAW_BUFFER14", "DRAW_BUFFER15", "DRAW_BUFFER2", "DRAW_BUFFER3", "DRAW_BUFFER4",
           "DRAW_BUFFER5", "DRAW_BUFFER6", "DRAW_BUFFER7", "DRAW_BUFFER8", "DRAW_BUFFER9", "DRAW_FRAMEBUFFER",
           "DRAW_FRAMEBUFFER_BINDING", "DRAW_INDIRECT_BUFFER", "DRAW_INDIRECT_BUFFER_BINDING", "DST_ALPHA", "DST_COLOR",
           "DYNAMIC_COPY", "DYNAMIC_DRAW", "DYNAMIC_READ", "ELEMENT_ARRAY_BARRIER_BIT", "ELEMENT_ARRAY_BUFFER",
           "ELEMENT_ARRAY_BUFFER_BINDING", "EQUAL", "EXTENSIONS", "FALSE", "FASTEST", "FIXED", "FLOAT",
           "FLOAT_32_UNSIGNED_INT_24_8_REV", "FLOAT_MAT2", "FLOAT_MAT2x3", "FLOAT_MAT2x4", "FLOAT_MAT3", "FLOAT_MAT3x2",
           "FLOAT_MAT3x4", "FLOAT_MAT4", "FLOAT_MAT4x2", "FLOAT_MAT4x3", "FLOAT_VEC2", "FLOAT_VEC3", "FLOAT_VEC4",
           "FRAGMENT_SHADER", "FRAGMENT_SHADER_BIT", "FRAGMENT_SHADER_DERIVATIVE_HINT", "FRAMEBUFFER",
           "FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE", "FRAMEBUFFER_ATTACHMENT_BLUE_SIZE",
           "FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING", "FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE",
           "FRAMEBUFFER_ATTACHMENT_DEPTH_SIZE", "FRAMEBUFFER_ATTACHMENT_GREEN_SIZE",
           "FRAMEBUFFER_ATTACHMENT_OBJECT_NAME", "FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE",
           "FRAMEBUFFER_ATTACHMENT_RED_SIZE", "FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE",
           "FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE", "FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER",
           "FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL", "FRAMEBUFFER_BARRIER_BIT", "FRAMEBUFFER_BINDING",
           "FRAMEBUFFER_COMPLETE", "FRAMEBUFFER_DEFAULT", "FRAMEBUFFER_DEFAULT_FIXED_SAMPLE_LOCATIONS",
           "FRAMEBUFFER_DEFAULT_HEIGHT", "FRAMEBUFFER_DEFAULT_SAMPLES", "FRAMEBUFFER_DEFAULT_WIDTH",
           "FRAMEBUFFER_INCOMPLETE_ATTACHMENT", "FRAMEBUFFER_INCOMPLETE_DIMENSIONS",
           "FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT", "FRAMEBUFFER_INCOMPLETE_MULTISAMPLE", "FRAMEBUFFER_UNDEFINED",
           "FRAMEBUFFER_UNSUPPORTED", "FRONT", "FRONT_AND_BACK", "FRONT_FACE", "FUNC_ADD", "FUNC_REVERSE_SUBTRACT",
           "FUNC_SUBTRACT", "GENERATE_MIPMAP_HINT", "GEQUAL", "GREATER", "GREEN", "GREEN_BITS", "HALF_FLOAT", "HALF_NV",
           "HIGH_FLOAT", "HIGH_INT", "IMAGE_2D", "IMAGE_2D_ARRAY", "IMAGE_3D", "IMAGE_BINDING_ACCESS",
           "IMAGE_BINDING_FORMAT", "IMAGE_BINDING_LAYER", "IMAGE_BINDING_LAYERED", "IMAGE_BINDING_LEVEL",
           "IMAGE_BINDING_NAME", "IMAGE_CUBE", "IMAGE_FORMAT_COMPATIBILITY_BY_CLASS",
           "IMAGE_FORMAT_COMPATIBILITY_BY_SIZE", "IMAGE_FORMAT_COMPATIBILITY_TYPE", "IMPLEMENTATION_COLOR_READ_FORMAT",
           "IMPLEMENTATION_COLOR_READ_TYPE", "INCR", "INCR_WRAP", "INFO_LOG_LENGTH", "INT", "INTERLEAVED_ATTRIBS",
           "INT_2_10_10_10_REV", "INT_IMAGE_2D", "INT_IMAGE_2D_ARRAY", "INT_IMAGE_3D", "INT_IMAGE_CUBE",
           "INT_SAMPLER_2D", "INT_SAMPLER_2D_ARRAY", "INT_SAMPLER_2D_MULTISAMPLE", "INT_SAMPLER_3D", "INT_SAMPLER_CUBE",
           "INT_VEC2", "INT_VEC3", "INT_VEC4", "INVALID_ENUM", "INVALID_FRAMEBUFFER_OPERATION", "INVALID_INDEX",
           "INVALID_OPERATION", "INVALID_VALUE", "INVERT", "IS_ROW_MAJOR", "KEEP", "LEQUAL", "LESS", "LINEAR",
           "LINEAR_MIPMAP_LINEAR", "LINEAR_MIPMAP_NEAREST", "LINES", "LINE_LOOP", "LINE_STRIP", "LINE_WIDTH",
           "LINK_STATUS", "LOCATION", "LOW_FLOAT", "LOW_INT", "LUMINANCE", "LUMINANCE_ALPHA", "MAJOR_VERSION",
           "MAP_FLUSH_EXPLICIT_BIT", "MAP_INVALIDATE_BUFFER_BIT", "MAP_INVALIDATE_RANGE_BIT", "MAP_READ_BIT",
           "MAP_UNSYNCHRONIZED_BIT", "MAP_WRITE_BIT", "MATRIX_STRIDE", "MAX", "MAX_3D_TEXTURE_SIZE",
           "MAX_ARRAY_TEXTURE_LAYERS", "MAX_ATOMIC_COUNTER_BUFFER_BINDINGS", "MAX_ATOMIC_COUNTER_BUFFER_SIZE",
           "MAX_COLOR_ATTACHMENTS", "MAX_COLOR_TEXTURE_SAMPLES", "MAX_COMBINED_ATOMIC_COUNTERS",
           "MAX_COMBINED_ATOMIC_COUNTER_BUFFERS", "MAX_COMBINED_COMPUTE_UNIFORM_COMPONENTS",
           "MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS", "MAX_COMBINED_IMAGE_UNIFORMS",
           "MAX_COMBINED_SHADER_OUTPUT_RESOURCES", "MAX_COMBINED_SHADER_STORAGE_BLOCKS",
           "MAX_COMBINED_TEXTURE_IMAGE_UNITS", "MAX_COMBINED_UNIFORM_BLOCKS", "MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS",
           "MAX_COMPUTE_ATOMIC_COUNTERS", "MAX_COMPUTE_ATOMIC_COUNTER_BUFFERS", "MAX_COMPUTE_IMAGE_UNIFORMS",
           "MAX_COMPUTE_SHADER_STORAGE_BLOCKS", "MAX_COMPUTE_SHARED_MEMORY_SIZE", "MAX_COMPUTE_TEXTURE_IMAGE_UNITS",
           "MAX_COMPUTE_UNIFORM_BLOCKS", "MAX_COMPUTE_UNIFORM_COMPONENTS", "MAX_COMPUTE_WORK_GROUP_COUNT",
           "MAX_COMPUTE_WORK_GROUP_INVOCATIONS", "MAX_COMPUTE_WORK_GROUP_SIZE", "MAX_CUBE_MAP_TEXTURE_SIZE",
           "MAX_DEPTH_TEXTURE_SAMPLES", "MAX_DRAW_BUFFERS", "MAX_ELEMENTS_INDICES", "MAX_ELEMENTS_VERTICES",
           "MAX_ELEMENT_INDEX", "MAX_FRAGMENT_ATOMIC_COUNTERS", "MAX_FRAGMENT_ATOMIC_COUNTER_BUFFERS",
           "MAX_FRAGMENT_IMAGE_UNIFORMS", "MAX_FRAGMENT_INPUT_COMPONENTS", "MAX_FRAGMENT_SHADER_STORAGE_BLOCKS",
           "MAX_FRAGMENT_UNIFORM_BLOCKS", "MAX_FRAGMENT_UNIFORM_COMPONENTS", "MAX_FRAGMENT_UNIFORM_VECTORS",
           "MAX_FRAMEBUFFER_HEIGHT", "MAX_FRAMEBUFFER_SAMPLES", "MAX_FRAMEBUFFER_WIDTH", "MAX_IMAGE_UNITS",
           "MAX_INTEGER_SAMPLES", "MAX_NAME_LENGTH", "MAX_NUM_ACTIVE_VARIABLES", "MAX_PROGRAM_TEXEL_OFFSET",
           "MAX_PROGRAM_TEXTURE_GATHER_OFFSET", "MAX_RENDERBUFFER_SIZE", "MAX_SAMPLES", "MAX_SAMPLE_MASK_WORDS",
           "MAX_SERVER_WAIT_TIMEOUT", "MAX_SHADER_STORAGE_BLOCK_SIZE", "MAX_SHADER_STORAGE_BUFFER_BINDINGS",
           "MAX_TEXTURE_IMAGE_UNITS", "MAX_TEXTURE_LOD_BIAS", "MAX_TEXTURE_SIZE",
           "MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS", "MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS",
           "MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS", "MAX_UNIFORM_BLOCK_SIZE", "MAX_UNIFORM_BUFFER_BINDINGS",
           "MAX_UNIFORM_LOCATIONS", "MAX_VARYING_COMPONENTS", "MAX_VARYING_VECTORS", "MAX_VERTEX_ATOMIC_COUNTERS",
           "MAX_VERTEX_ATOMIC_COUNTER_BUFFERS", "MAX_VERTEX_ATTRIBS", "MAX_VERTEX_ATTRIB_BINDINGS",
           "MAX_VERTEX_ATTRIB_RELATIVE_OFFSET", "MAX_VERTEX_ATTRIB_STRIDE", "MAX_VERTEX_IMAGE_UNIFORMS",
           "MAX_VERTEX_OUTPUT_COMPONENTS", "MAX_VERTEX_SHADER_STORAGE_BLOCKS", "MAX_VERTEX_TEXTURE_IMAGE_UNITS",
           "MAX_VERTEX_UNIFORM_BLOCKS", "MAX_VERTEX_UNIFORM_COMPONENTS", "MAX_VERTEX_UNIFORM_VECTORS",
           "MAX_VIEWPORT_DIMS", "MEDIUM_FLOAT", "MEDIUM_INT", "MIN", "MINOR_VERSION", "MIN_PROGRAM_TEXEL_OFFSET",
           "MIN_PROGRAM_TEXTURE_GATHER_OFFSET", "MIRRORED_REPEAT", "NAME_LENGTH", "NEAREST", "NEAREST_MIPMAP_LINEAR",
           "NEAREST_MIPMAP_NEAREST", "NEVER", "NICEST", "NONE", "NOTEQUAL", "NO_ERROR", "NUM_ACTIVE_VARIABLES",
           "NUM_COMPRESSED_TEXTURE_FORMATS", "NUM_EXTENSIONS", "NUM_PROGRAM_BINARY_FORMATS", "NUM_SAMPLE_COUNTS",
           "NUM_SHADER_BINARY_FORMATS", "OBJECT_TYPE", "OFFSET", "ONE", "ONE_MINUS_CONSTANT_ALPHA",
           "ONE_MINUS_CONSTANT_COLOR", "ONE_MINUS_DST_ALPHA", "ONE_MINUS_DST_COLOR", "ONE_MINUS_SRC_ALPHA",
           "ONE_MINUS_SRC_COLOR", "OUT_OF_MEMORY", "PACK_ALIGNMENT", "PACK_ROW_LENGTH", "PACK_SKIP_PIXELS",
           "PACK_SKIP_ROWS", "PIXEL_BUFFER_BARRIER_BIT", "PIXEL_PACK_BUFFER", "PIXEL_PACK_BUFFER_BINDING",
           "PIXEL_UNPACK_BUFFER", "PIXEL_UNPACK_BUFFER_BINDING", "POINTS", "POLYGON_OFFSET_FACTOR",
           "POLYGON_OFFSET_FILL", "POLYGON_OFFSET_UNITS", "PRIMITIVE_RESTART_FIXED_INDEX", "PROGRAM_BINARY_FORMATS",
           "PROGRAM_BINARY_LENGTH", "PROGRAM_BINARY_RETRIEVABLE_HINT", "PROGRAM_INPUT", "PROGRAM_OUTPUT",
           "PROGRAM_PIPELINE_BINDING", "PROGRAM_SEPARABLE", "QUERY_RESULT", "QUERY_RESULT_AVAILABLE", "R11F_G11F_B10F",
           "R16F", "R16I", "R16UI", "R32F", "R32I", "R32UI", "R8", "R8I", "R8UI", "R8_SNORM", "RASTERIZER_DISCARD",
           "READ_BUFFER", "READ_FRAMEBUFFER", "READ_FRAMEBUFFER_BINDING", "READ_ONLY", "READ_WRITE", "RED", "RED_BITS",
           "RED_INTEGER", "REFERENCED_BY_COMPUTE_SHADER", "REFERENCED_BY_FRAGMENT_SHADER",
           "REFERENCED_BY_VERTEX_SHADER", "RENDERBUFFER", "RENDERBUFFER_ALPHA_SIZE", "RENDERBUFFER_BINDING",
           "RENDERBUFFER_BLUE_SIZE", "RENDERBUFFER_DEPTH_SIZE", "RENDERBUFFER_GREEN_SIZE", "RENDERBUFFER_HEIGHT",
           "RENDERBUFFER_INTERNAL_FORMAT", "RENDERBUFFER_RED_SIZE", "RENDERBUFFER_SAMPLES", "RENDERBUFFER_STENCIL_SIZE",
           "RENDERBUFFER_WIDTH", "RENDERER", "REPEAT", "REPLACE", "RG", "RG16F", "RG16I", "RG16UI", "RG32F", "RG32I",
           "RG32UI", "RG8", "RG8I", "RG8UI", "RG8_SNORM", "RGB", "RGB10_A2", "RGB10_A2UI", "RGB16F", "RGB16I",
           "RGB16UI", "RGB32F", "RGB32I", "RGB32UI", "RGB565", "RGB5_A1", "RGB8", "RGB8I", "RGB8UI", "RGB8_SNORM",
           "RGB9_E5", "RGBA", "RGBA16F", "RGBA16I", "RGBA16UI", "RGBA32F", "RGBA32I", "RGBA32UI", "RGBA4", "RGBA8",
           "RGBA8I", "RGBA8UI", "RGBA8_SNORM", "RGBA_INTEGER", "RGB_INTEGER", "RG_INTEGER", "SAMPLER_2D",
           "SAMPLER_2D_ARRAY", "SAMPLER_2D_ARRAY_SHADOW", "SAMPLER_2D_MULTISAMPLE", "SAMPLER_2D_SHADOW", "SAMPLER_3D",
           "SAMPLER_BINDING", "SAMPLER_CUBE", "SAMPLER_CUBE_SHADOW", "SAMPLES", "SAMPLE_ALPHA_TO_COVERAGE",
           "SAMPLE_BUFFERS", "SAMPLE_COVERAGE", "SAMPLE_COVERAGE_INVERT", "SAMPLE_COVERAGE_VALUE", "SAMPLE_MASK",
           "SAMPLE_MASK_VALUE", "SAMPLE_POSITION", "SCISSOR_BOX", "SCISSOR_TEST", "SEPARATE_ATTRIBS",
           "SHADER_BINARY_FORMATS", "SHADER_COMPILER", "SHADER_IMAGE_ACCESS_BARRIER_BIT", "SHADER_SOURCE_LENGTH",
           "SHADER_STORAGE_BARRIER_BIT", "SHADER_STORAGE_BLOCK", "SHADER_STORAGE_BUFFER",
           "SHADER_STORAGE_BUFFER_BINDING", "SHADER_STORAGE_BUFFER_OFFSET_ALIGNMENT", "SHADER_STORAGE_BUFFER_SIZE",
           "SHADER_STORAGE_BUFFER_START", "SHADER_TYPE", "SHADING_LANGUAGE_VERSION", "SHORT", "SIGNALED",
           "SIGNED_NORMALIZED", "SRC_ALPHA", "SRC_ALPHA_SATURATE", "SRC_COLOR", "SRGB", "SRGB8", "SRGB8_ALPHA8",
           "STATIC_COPY", "STATIC_DRAW", "STATIC_READ", "STENCIL", "STENCIL_ATTACHMENT", "STENCIL_BACK_FAIL",
           "STENCIL_BACK_FUNC", "STENCIL_BACK_PASS_DEPTH_FAIL", "STENCIL_BACK_PASS_DEPTH_PASS", "STENCIL_BACK_REF",
           "STENCIL_BACK_VALUE_MASK", "STENCIL_BACK_WRITEMASK", "STENCIL_BITS", "STENCIL_BUFFER_BIT",
           "STENCIL_CLEAR_VALUE", "STENCIL_FAIL", "STENCIL_FUNC", "STENCIL_INDEX", "STENCIL_INDEX8",
           "STENCIL_PASS_DEPTH_FAIL", "STENCIL_PASS_DEPTH_PASS", "STENCIL_REF", "STENCIL_TEST", "STENCIL_VALUE_MASK",
           "STENCIL_WRITEMASK", "STREAM_COPY", "STREAM_DRAW", "STREAM_READ", "SUBPIXEL_BITS", "SYNC_CONDITION",
           "SYNC_FENCE", "SYNC_FLAGS", "SYNC_FLUSH_COMMANDS_BIT", "SYNC_GPU_COMMANDS_COMPLETE", "SYNC_STATUS",
           "TEXTURE", "TEXTURE0", "TEXTURE1", "TEXTURE10", "TEXTURE11", "TEXTURE12", "TEXTURE13", "TEXTURE14",
           "TEXTURE15", "TEXTURE16", "TEXTURE17", "TEXTURE18", "TEXTURE19", "TEXTURE2", "TEXTURE20", "TEXTURE21",
           "TEXTURE22", "TEXTURE23", "TEXTURE24", "TEXTURE25", "TEXTURE26", "TEXTURE27", "TEXTURE28", "TEXTURE29",
           "TEXTURE3", "TEXTURE30", "TEXTURE31", "TEXTURE4", "TEXTURE5", "TEXTURE6", "TEXTURE7", "TEXTURE8", "TEXTURE9",
           "TEXTURE_2D", "TEXTURE_2D_ARRAY", "TEXTURE_2D_MULTISAMPLE", "TEXTURE_3D", "TEXTURE_ALPHA_SIZE",
           "TEXTURE_ALPHA_TYPE", "TEXTURE_BASE_LEVEL", "TEXTURE_BINDING_2D", "TEXTURE_BINDING_2D_ARRAY",
           "TEXTURE_BINDING_2D_MULTISAMPLE", "TEXTURE_BINDING_3D", "TEXTURE_BINDING_CUBE_MAP", "TEXTURE_BLUE_SIZE",
           "TEXTURE_BLUE_TYPE", "TEXTURE_COMPARE_FUNC", "TEXTURE_COMPARE_MODE", "TEXTURE_COMPRESSED",
           "TEXTURE_CUBE_MAP", "TEXTURE_CUBE_MAP_NEGATIVE_X", "TEXTURE_CUBE_MAP_NEGATIVE_Y",
           "TEXTURE_CUBE_MAP_NEGATIVE_Z", "TEXTURE_CUBE_MAP_POSITIVE_X", "TEXTURE_CUBE_MAP_POSITIVE_Y",
           "TEXTURE_CUBE_MAP_POSITIVE_Z", "TEXTURE_DEPTH", "TEXTURE_DEPTH_SIZE", "TEXTURE_DEPTH_TYPE",
           "TEXTURE_FETCH_BARRIER_BIT", "TEXTURE_FIXED_SAMPLE_LOCATIONS", "TEXTURE_GREEN_SIZE", "TEXTURE_GREEN_TYPE",
           "TEXTURE_HEIGHT", "TEXTURE_IMMUTABLE_FORMAT", "TEXTURE_IMMUTABLE_LEVELS", "TEXTURE_INTERNAL_FORMAT",
           "TEXTURE_MAG_FILTER", "TEXTURE_MAX_LEVEL", "TEXTURE_MAX_LOD", "TEXTURE_MIN_FILTER", "TEXTURE_MIN_LOD",
           "TEXTURE_RED_SIZE", "TEXTURE_RED_TYPE", "TEXTURE_SAMPLES", "TEXTURE_SHARED_SIZE", "TEXTURE_STENCIL_SIZE",
           "TEXTURE_SWIZZLE_A", "TEXTURE_SWIZZLE_B", "TEXTURE_SWIZZLE_G", "TEXTURE_SWIZZLE_R",
           "TEXTURE_UPDATE_BARRIER_BIT", "TEXTURE_WIDTH", "TEXTURE_WRAP_R", "TEXTURE_WRAP_S", "TEXTURE_WRAP_T",
           "TIMEOUT_EXPIRED", "TIMEOUT_IGNORED", "TOP_LEVEL_ARRAY_SIZE", "TOP_LEVEL_ARRAY_STRIDE", "TRANSFORM_FEEDBACK",
           "TRANSFORM_FEEDBACK_ACTIVE", "TRANSFORM_FEEDBACK_BARRIER_BIT", "TRANSFORM_FEEDBACK_BINDING",
           "TRANSFORM_FEEDBACK_BUFFER", "TRANSFORM_FEEDBACK_BUFFER_BINDING", "TRANSFORM_FEEDBACK_BUFFER_MODE",
           "TRANSFORM_FEEDBACK_BUFFER_SIZE", "TRANSFORM_FEEDBACK_BUFFER_START", "TRANSFORM_FEEDBACK_PAUSED",
           "TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN", "TRANSFORM_FEEDBACK_VARYING", "TRANSFORM_FEEDBACK_VARYINGS",
           "TRANSFORM_FEEDBACK_VARYING_MAX_LENGTH", "TRIANGLES", "TRIANGLE_FAN", "TRIANGLE_STRIP", "TRUE", "TYPE",
           "UNIFORM", "UNIFORM_ARRAY_STRIDE", "UNIFORM_BARRIER_BIT", "UNIFORM_BLOCK", "UNIFORM_BLOCK_ACTIVE_UNIFORMS",
           "UNIFORM_BLOCK_ACTIVE_UNIFORM_INDICES", "UNIFORM_BLOCK_BINDING", "UNIFORM_BLOCK_DATA_SIZE",
           "UNIFORM_BLOCK_INDEX", "UNIFORM_BLOCK_NAME_LENGTH", "UNIFORM_BLOCK_REFERENCED_BY_FRAGMENT_SHADER",
           "UNIFORM_BLOCK_REFERENCED_BY_VERTEX_SHADER", "UNIFORM_BUFFER", "UNIFORM_BUFFER_BINDING",
           "UNIFORM_BUFFER_OFFSET_ALIGNMENT", "UNIFORM_BUFFER_SIZE", "UNIFORM_BUFFER_START", "UNIFORM_IS_ROW_MAJOR",
           "UNIFORM_MATRIX_STRIDE", "UNIFORM_NAME_LENGTH", "UNIFORM_OFFSET", "UNIFORM_SIZE", "UNIFORM_TYPE",
           "UNPACK_ALIGNMENT", "UNPACK_IMAGE_HEIGHT", "UNPACK_ROW_LENGTH", "UNPACK_SKIP_IMAGES", "UNPACK_SKIP_PIXELS",
           "UNPACK_SKIP_ROWS", "UNSIGNALED", "UNSIGNED_BYTE", "UNSIGNED_INT", "UNSIGNED_INT64",
           "UNSIGNED_INT_10F_11F_11F_REV", "UNSIGNED_INT_24_8", "UNSIGNED_INT_2_10_10_10_REV",
           "UNSIGNED_INT_5_9_9_9_REV", "UNSIGNED_INT_ATOMIC_COUNTER", "UNSIGNED_INT_IMAGE_2D",
           "UNSIGNED_INT_IMAGE_2D_ARRAY", "UNSIGNED_INT_IMAGE_3D", "UNSIGNED_INT_IMAGE_CUBE", "UNSIGNED_INT_SAMPLER_2D",
           "UNSIGNED_INT_SAMPLER_2D_ARRAY", "UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE", "UNSIGNED_INT_SAMPLER_3D",
           "UNSIGNED_INT_SAMPLER_CUBE", "UNSIGNED_INT_VEC2", "UNSIGNED_INT_VEC3", "UNSIGNED_INT_VEC4",
           "UNSIGNED_NORMALIZED", "UNSIGNED_SHORT", "UNSIGNED_SHORT_4_4_4_4", "UNSIGNED_SHORT_5_5_5_1",
           "UNSIGNED_SHORT_5_6_5", "VALIDATE_STATUS", "VENDOR", "VERSION", "VERTEX_ARRAY_BINDING",
           "VERTEX_ATTRIB_ARRAY_BARRIER_BIT", "VERTEX_ATTRIB_ARRAY_BUFFER_BINDING", "VERTEX_ATTRIB_ARRAY_DIVISOR",
           "VERTEX_ATTRIB_ARRAY_ENABLED", "VERTEX_ATTRIB_ARRAY_INTEGER", "VERTEX_ATTRIB_ARRAY_NORMALIZED",
           "VERTEX_ATTRIB_ARRAY_POINTER", "VERTEX_ATTRIB_ARRAY_SIZE", "VERTEX_ATTRIB_ARRAY_STRIDE",
           "VERTEX_ATTRIB_ARRAY_TYPE", "VERTEX_ATTRIB_BINDING", "VERTEX_ATTRIB_RELATIVE_OFFSET",
           "VERTEX_BINDING_BUFFER", "VERTEX_BINDING_DIVISOR", "VERTEX_BINDING_OFFSET", "VERTEX_BINDING_STRIDE",
           "VERTEX_SHADER", "VERTEX_SHADER_BIT", "VIEWPORT", "VOID_P", "WAIT_FAILED", "WRITE_ONLY", "ZERO", "bitfield",
           "boolean", "byte", "char", "charARB", "clampd", "clampf", "clampx", "double", "double_2", "double_3",
           "double_4", "eglImageOES", "enum", "fixed", "float", "float_2", "float_3", "float_4", "halfARB", "halfNV",
           "handle", "handleARB", "int", "int64", "int64EXT", "intptr", "intptrARB", "short", "sizei", "sizeiptr",
           "sizeiptrARB", "sync", "ubyte", "ubyte_3", "uint", "uint64", "uint64EXT", "ulong", "ushort",
           "vdpauSurfaceNV", "void", "voidp", "arrays", "as_8_bit", "bytes", "c_int", "constant", "contextdata",
           "converters", "ctypes", "ctypes_version", "extensions", "activeShaderProgram", "activeTexture",
           "attachShader", "beginQuery", "beginTransformFeedback", "bindAttribLocation", "bindBuffer", "bindBufferBase",
           "bindBufferRange", "bindFramebuffer", "bindImageTexture", "bindProgramPipeline", "bindRenderbuffer",
           "bindSampler", "bindTexture", "bindTransformFeedback", "bindVertexArray", "bindVertexBuffer", "blendColor",
           "blendEquation", "blendEquationSeparate", "blendFunc", "blendFuncSeparate", "blitFramebuffer", "bufferData",
           "bufferSubData", "checkFramebufferStatus", "clear", "clearBufferfi", "clearBufferfv", "clearBufferiv",
           "clearBufferuiv", "clearColor", "clearDepthf", "clearStencil", "clientWaitSync", "colorMask",
           "compileShader", "compressedTexImage2D", "compressedTexImage3D", "compressedTexSubImage2D",
           "compressedTexSubImage3D", "copyBufferSubData", "copyTexImage2D", "copyTexSubImage2D", "copyTexSubImage3D",
           "createProgram", "createShader", "createShaderProgramv", "cullFace", "deleteBuffers", "deleteFramebuffers",
           "deleteProgram", "deleteProgramPipelines", "deleteQueries", "deleteRenderbuffers", "deleteSamplers",
           "deleteShader", "deleteSync", "deleteTextures", "deleteTransformFeedbacks", "deleteVertexArrays",
           "depthFunc", "depthMask", "depthRangef", "detachShader", "disable", "disableVertexAttribArray",
           "dispatchCompute", "dispatchComputeIndirect", "drawArrays", "drawArraysIndirect", "drawArraysInstanced",
           "drawBuffers", "drawElements", "drawElementsIndirect", "drawElementsInstanced", "drawRangeElements",
           "enable", "enableVertexAttribArray", "endQuery", "endTransformFeedback", "fenceSync", "finish", "flush",
           "flushMappedBufferRange", "framebufferParameteri", "framebufferRenderbuffer", "framebufferTexture2D",
           "framebufferTextureLayer", "frontFace", "genBuffers", "genFramebuffers", "genProgramPipelines", "genQueries",
           "genRenderbuffers", "genSamplers", "genTextures", "genTransformFeedbacks", "genVertexArrays",
           "generateMipmap", "getActiveAttrib", "getActiveUniform", "getActiveUniformBlockName",
           "getActiveUniformBlockiv", "getActiveUniformsiv", "getAttachedShaders", "getAttribLocation", "getBooleani_v",
           "getBooleanv", "getBufferParameteri64v", "getBufferParameteriv", "getBufferPointerv", "getError",
           "getFloatv", "getFragDataLocation", "getFramebufferAttachmentParameteriv", "getFramebufferParameteriv",
           "getInteger64i_v", "getInteger64v", "getIntegeri_v", "getIntegerv", "getInternalformativ",
           "getMultisamplefv", "getProgramBinary", "getProgramInfoLog", "getProgramInterfaceiv",
           "getProgramPipelineInfoLog", "getProgramPipelineiv", "getProgramResourceIndex", "getProgramResourceLocation",
           "getProgramResourceName", "getProgramResourceiv", "getProgramiv", "getQueryObjectuiv", "getQueryiv",
           "getRenderbufferParameteriv", "getSamplerParameterfv", "getSamplerParameteriv", "getShaderInfoLog",
           "getShaderPrecisionFormat", "getShaderSource", "getShaderiv", "getString", "getStringi", "getSynciv",
           "getTexLevelParameterfv", "getTexLevelParameteriv", "getTexParameterfv", "getTexParameteriv",
           "getTransformFeedbackVarying", "getUniformBlockIndex", "getUniformIndices", "getUniformLocation",
           "getUniformfv", "getUniformiv", "getUniformuiv", "getVertexAttribIiv", "getVertexAttribIuiv",
           "getVertexAttribPointerv", "getVertexAttribfv", "getVertexAttribiv", "hint", "initGles220VERSION",
           "initGles330VERSION", "initGles331VERSION", "invalidateFramebuffer", "invalidateSubFramebuffer", "isBuffer",
           "isEnabled", "isFramebuffer", "isProgram", "isProgramPipeline", "isQuery", "isRenderbuffer", "isSampler",
           "isShader", "isSync", "isTexture", "isTransformFeedback", "isVertexArray", "lineWidth", "linkProgram",
           "mapBufferRange", "memoryBarrier", "memoryBarrierByRegion", "pauseTransformFeedback", "pixelStorei",
           "polygonOffset", "programBinary", "programParameteri", "programUniform1f", "programUniform1fv",
           "programUniform1i", "programUniform1iv", "programUniform1ui", "programUniform1uiv", "programUniform2f",
           "programUniform2fv", "programUniform2i", "programUniform2iv", "programUniform2ui", "programUniform2uiv",
           "programUniform3f", "programUniform3fv", "programUniform3i", "programUniform3iv", "programUniform3ui",
           "programUniform3uiv", "programUniform4f", "programUniform4fv", "programUniform4i", "programUniform4iv",
           "programUniform4ui", "programUniform4uiv", "programUniformMatrix2fv", "programUniformMatrix2x3fv",
           "programUniformMatrix2x4fv", "programUniformMatrix3fv", "programUniformMatrix3x2fv",
           "programUniformMatrix3x4fv", "programUniformMatrix4fv", "programUniformMatrix4x2fv",
           "programUniformMatrix4x3fv", "readBuffer", "readPixels", "releaseShaderCompiler", "renderbufferStorage",
           "renderbufferStorageMultisample", "resumeTransformFeedback", "sampleCoverage", "sampleMaski",
           "samplerParameterf", "samplerParameterfv", "samplerParameteri", "samplerParameteriv", "scissor",
           "shaderBinary", "shaderSource", "stencilFunc", "stencilFuncSeparate", "stencilMask", "stencilMaskSeparate",
           "stencilOp", "stencilOpSeparate", "texImage2D", "texImage3D", "texParameterf", "texParameterfv",
           "texParameteri", "texParameteriv", "texStorage2D", "texStorage2DMultisample", "texStorage3D",
           "texSubImage2D", "texSubImage3D", "transformFeedbackVaryings", "uniform1f", "uniform1fv", "uniform1i",
           "uniform1iv", "uniform1ui", "uniform1uiv", "uniform2f", "uniform2fv", "uniform2i", "uniform2iv",
           "uniform2ui", "uniform2uiv", "uniform3f", "uniform3fv", "uniform3i", "uniform3iv", "uniform3ui",
           "uniform3uiv", "uniform4f", "uniform4fv", "uniform4i", "uniform4iv", "uniform4ui", "uniform4uiv",
           "uniformBlockBinding", "uniformMatrix2fv", "uniformMatrix2x3fv", "uniformMatrix2x4fv", "uniformMatrix3fv",
           "uniformMatrix3x2fv", "uniformMatrix3x4fv", "uniformMatrix4fv", "uniformMatrix4x2fv", "uniformMatrix4x3fv",
           "unmapBuffer", "useProgram", "useProgramStages", "validateProgram", "validateProgramPipeline",
           "vertexAttrib1f", "vertexAttrib1fv", "vertexAttrib2f", "vertexAttrib2fv", "vertexAttrib3f",
           "vertexAttrib3fv", "vertexAttrib4f", "vertexAttrib4fv", "vertexAttribBinding", "vertexAttribDivisor",
           "vertexAttribFormat", "vertexAttribI4i", "vertexAttribI4iv", "vertexAttribI4ui", "vertexAttribI4uiv",
           "vertexAttribIFormat", "vertexAttribIPointer", "vertexAttribPointer", "vertexBindingDivisor", "viewport",
           "waitSync", "int32_t", "int64_t", "long", "platform", "size_t", "sizeof", "unicode", "wrapper"]

ARRAY_TYPE_TO_CONSTANT = GLES3.ARRAY_TYPE_TO_CONSTANT
Constant = GLES3.Constant
DEBUGPROC = GLES3.GLDEBUGPROC
DEBUGPROCAMD = GLES3.GLDEBUGPROCAMD
DEBUGPROCARB = GLES3.GLDEBUGPROCARB
DEBUGPROCKHR = GLES3.GLDEBUGPROCKHR
ACTIVE_ATOMIC_COUNTER_BUFFERS = GLES3.GL_ACTIVE_ATOMIC_COUNTER_BUFFERS
ACTIVE_ATTRIBUTES = GLES3.GL_ACTIVE_ATTRIBUTES
ACTIVE_ATTRIBUTE_MAX_LENGTH = GLES3.GL_ACTIVE_ATTRIBUTE_MAX_LENGTH
ACTIVE_PROGRAM = GLES3.GL_ACTIVE_PROGRAM
ACTIVE_RESOURCES = GLES3.GL_ACTIVE_RESOURCES
ACTIVE_TEXTURE = GLES3.GL_ACTIVE_TEXTURE
ACTIVE_UNIFORMS = GLES3.GL_ACTIVE_UNIFORMS
ACTIVE_UNIFORM_BLOCKS = GLES3.GL_ACTIVE_UNIFORM_BLOCKS
ACTIVE_UNIFORM_BLOCK_MAX_NAME_LENGTH = GLES3.GL_ACTIVE_UNIFORM_BLOCK_MAX_NAME_LENGTH
ACTIVE_UNIFORM_MAX_LENGTH = GLES3.GL_ACTIVE_UNIFORM_MAX_LENGTH
ACTIVE_VARIABLES = GLES3.GL_ACTIVE_VARIABLES
ALIASED_LINE_WIDTH_RANGE = GLES3.GL_ALIASED_LINE_WIDTH_RANGE
ALIASED_POINT_SIZE_RANGE = GLES3.GL_ALIASED_POINT_SIZE_RANGE
ALL_BARRIER_BITS = GLES3.GL_ALL_BARRIER_BITS
ALL_SHADER_BITS = GLES3.GL_ALL_SHADER_BITS
ALPHA = GLES3.GL_ALPHA
ALPHA_BITS = GLES3.GL_ALPHA_BITS
ALREADY_SIGNALED = GLES3.GL_ALREADY_SIGNALED
ALWAYS = GLES3.GL_ALWAYS
ANY_SAMPLES_PASSED = GLES3.GL_ANY_SAMPLES_PASSED
ANY_SAMPLES_PASSED_CONSERVATIVE = GLES3.GL_ANY_SAMPLES_PASSED_CONSERVATIVE
ARRAY_BUFFER = GLES3.GL_ARRAY_BUFFER
ARRAY_BUFFER_BINDING = GLES3.GL_ARRAY_BUFFER_BINDING
ARRAY_SIZE = GLES3.GL_ARRAY_SIZE
ARRAY_STRIDE = GLES3.GL_ARRAY_STRIDE
ATOMIC_COUNTER_BARRIER_BIT = GLES3.GL_ATOMIC_COUNTER_BARRIER_BIT
ATOMIC_COUNTER_BUFFER = GLES3.GL_ATOMIC_COUNTER_BUFFER
ATOMIC_COUNTER_BUFFER_BINDING = GLES3.GL_ATOMIC_COUNTER_BUFFER_BINDING
ATOMIC_COUNTER_BUFFER_INDEX = GLES3.GL_ATOMIC_COUNTER_BUFFER_INDEX
ATOMIC_COUNTER_BUFFER_SIZE = GLES3.GL_ATOMIC_COUNTER_BUFFER_SIZE
ATOMIC_COUNTER_BUFFER_START = GLES3.GL_ATOMIC_COUNTER_BUFFER_START
ATTACHED_SHADERS = GLES3.GL_ATTACHED_SHADERS
BACK = GLES3.GL_BACK
BLEND = GLES3.GL_BLEND
BLEND_COLOR = GLES3.GL_BLEND_COLOR
BLEND_DST_ALPHA = GLES3.GL_BLEND_DST_ALPHA
BLEND_DST_RGB = GLES3.GL_BLEND_DST_RGB
BLEND_EQUATION = GLES3.GL_BLEND_EQUATION
BLEND_EQUATION_ALPHA = GLES3.GL_BLEND_EQUATION_ALPHA
BLEND_EQUATION_RGB = GLES3.GL_BLEND_EQUATION_RGB
BLEND_SRC_ALPHA = GLES3.GL_BLEND_SRC_ALPHA
BLEND_SRC_RGB = GLES3.GL_BLEND_SRC_RGB
BLOCK_INDEX = GLES3.GL_BLOCK_INDEX
BLUE = GLES3.GL_BLUE
BLUE_BITS = GLES3.GL_BLUE_BITS
BOOL = GLES3.GL_BOOL
BOOL_VEC2 = GLES3.GL_BOOL_VEC2
BOOL_VEC3 = GLES3.GL_BOOL_VEC3
BOOL_VEC4 = GLES3.GL_BOOL_VEC4
BUFFER_ACCESS_FLAGS = GLES3.GL_BUFFER_ACCESS_FLAGS
BUFFER_BINDING = GLES3.GL_BUFFER_BINDING
BUFFER_DATA_SIZE = GLES3.GL_BUFFER_DATA_SIZE
BUFFER_MAPPED = GLES3.GL_BUFFER_MAPPED
BUFFER_MAP_LENGTH = GLES3.GL_BUFFER_MAP_LENGTH
BUFFER_MAP_OFFSET = GLES3.GL_BUFFER_MAP_OFFSET
BUFFER_MAP_POINTER = GLES3.GL_BUFFER_MAP_POINTER
BUFFER_SIZE = GLES3.GL_BUFFER_SIZE
BUFFER_UPDATE_BARRIER_BIT = GLES3.GL_BUFFER_UPDATE_BARRIER_BIT
BUFFER_USAGE = GLES3.GL_BUFFER_USAGE
BUFFER_VARIABLE = GLES3.GL_BUFFER_VARIABLE
BYTE = GLES3.GL_BYTE
CCW = GLES3.GL_CCW
CHAR = GLES3.GL_CHAR
CLAMP_TO_EDGE = GLES3.GL_CLAMP_TO_EDGE
COLOR = GLES3.GL_COLOR
COLOR_ATTACHMENT0 = GLES3.GL_COLOR_ATTACHMENT0
COLOR_ATTACHMENT1 = GLES3.GL_COLOR_ATTACHMENT1
COLOR_ATTACHMENT10 = GLES3.GL_COLOR_ATTACHMENT10
COLOR_ATTACHMENT11 = GLES3.GL_COLOR_ATTACHMENT11
COLOR_ATTACHMENT12 = GLES3.GL_COLOR_ATTACHMENT12
COLOR_ATTACHMENT13 = GLES3.GL_COLOR_ATTACHMENT13
COLOR_ATTACHMENT14 = GLES3.GL_COLOR_ATTACHMENT14
COLOR_ATTACHMENT15 = GLES3.GL_COLOR_ATTACHMENT15
COLOR_ATTACHMENT16 = GLES3.GL_COLOR_ATTACHMENT16
COLOR_ATTACHMENT17 = GLES3.GL_COLOR_ATTACHMENT17
COLOR_ATTACHMENT18 = GLES3.GL_COLOR_ATTACHMENT18
COLOR_ATTACHMENT19 = GLES3.GL_COLOR_ATTACHMENT19
COLOR_ATTACHMENT2 = GLES3.GL_COLOR_ATTACHMENT2
COLOR_ATTACHMENT20 = GLES3.GL_COLOR_ATTACHMENT20
COLOR_ATTACHMENT21 = GLES3.GL_COLOR_ATTACHMENT21
COLOR_ATTACHMENT22 = GLES3.GL_COLOR_ATTACHMENT22
COLOR_ATTACHMENT23 = GLES3.GL_COLOR_ATTACHMENT23
COLOR_ATTACHMENT24 = GLES3.GL_COLOR_ATTACHMENT24
COLOR_ATTACHMENT25 = GLES3.GL_COLOR_ATTACHMENT25
COLOR_ATTACHMENT26 = GLES3.GL_COLOR_ATTACHMENT26
COLOR_ATTACHMENT27 = GLES3.GL_COLOR_ATTACHMENT27
COLOR_ATTACHMENT28 = GLES3.GL_COLOR_ATTACHMENT28
COLOR_ATTACHMENT29 = GLES3.GL_COLOR_ATTACHMENT29
COLOR_ATTACHMENT3 = GLES3.GL_COLOR_ATTACHMENT3
COLOR_ATTACHMENT30 = GLES3.GL_COLOR_ATTACHMENT30
COLOR_ATTACHMENT31 = GLES3.GL_COLOR_ATTACHMENT31
COLOR_ATTACHMENT4 = GLES3.GL_COLOR_ATTACHMENT4
COLOR_ATTACHMENT5 = GLES3.GL_COLOR_ATTACHMENT5
COLOR_ATTACHMENT6 = GLES3.GL_COLOR_ATTACHMENT6
COLOR_ATTACHMENT7 = GLES3.GL_COLOR_ATTACHMENT7
COLOR_ATTACHMENT8 = GLES3.GL_COLOR_ATTACHMENT8
COLOR_ATTACHMENT9 = GLES3.GL_COLOR_ATTACHMENT9
COLOR_BUFFER_BIT = GLES3.GL_COLOR_BUFFER_BIT
COLOR_CLEAR_VALUE = GLES3.GL_COLOR_CLEAR_VALUE
COLOR_WRITEMASK = GLES3.GL_COLOR_WRITEMASK
COMMAND_BARRIER_BIT = GLES3.GL_COMMAND_BARRIER_BIT
COMPARE_REF_TO_TEXTURE = GLES3.GL_COMPARE_REF_TO_TEXTURE
COMPILE_STATUS = GLES3.GL_COMPILE_STATUS
COMPRESSED_R11_EAC = GLES3.GL_COMPRESSED_R11_EAC
COMPRESSED_RG11_EAC = GLES3.GL_COMPRESSED_RG11_EAC
COMPRESSED_RGB8_ETC2 = GLES3.GL_COMPRESSED_RGB8_ETC2
COMPRESSED_RGB8_PUNCHTHROUGH_ALPHA1_ETC2 = GLES3.GL_COMPRESSED_RGB8_PUNCHTHROUGH_ALPHA1_ETC2
COMPRESSED_RGBA8_ETC2_EAC = GLES3.GL_COMPRESSED_RGBA8_ETC2_EAC
COMPRESSED_SIGNED_R11_EAC = GLES3.GL_COMPRESSED_SIGNED_R11_EAC
COMPRESSED_SIGNED_RG11_EAC = GLES3.GL_COMPRESSED_SIGNED_RG11_EAC
COMPRESSED_SRGB8_ALPHA8_ETC2_EAC = GLES3.GL_COMPRESSED_SRGB8_ALPHA8_ETC2_EAC
COMPRESSED_SRGB8_ETC2 = GLES3.GL_COMPRESSED_SRGB8_ETC2
COMPRESSED_SRGB8_PUNCHTHROUGH_ALPHA1_ETC2 = GLES3.GL_COMPRESSED_SRGB8_PUNCHTHROUGH_ALPHA1_ETC2
COMPRESSED_TEXTURE_FORMATS = GLES3.GL_COMPRESSED_TEXTURE_FORMATS
COMPUTE_SHADER = GLES3.GL_COMPUTE_SHADER
COMPUTE_SHADER_BIT = GLES3.GL_COMPUTE_SHADER_BIT
COMPUTE_WORK_GROUP_SIZE = GLES3.GL_COMPUTE_WORK_GROUP_SIZE
CONDITION_SATISFIED = GLES3.GL_CONDITION_SATISFIED
CONSTANT_ALPHA = GLES3.GL_CONSTANT_ALPHA
CONSTANT_COLOR = GLES3.GL_CONSTANT_COLOR
COPY_READ_BUFFER = GLES3.GL_COPY_READ_BUFFER
COPY_READ_BUFFER_BINDING = GLES3.GL_COPY_READ_BUFFER_BINDING
COPY_WRITE_BUFFER = GLES3.GL_COPY_WRITE_BUFFER
COPY_WRITE_BUFFER_BINDING = GLES3.GL_COPY_WRITE_BUFFER_BINDING
CULL_FACE = GLES3.GL_CULL_FACE
CULL_FACE_MODE = GLES3.GL_CULL_FACE_MODE
CURRENT_PROGRAM = GLES3.GL_CURRENT_PROGRAM
CURRENT_QUERY = GLES3.GL_CURRENT_QUERY
CURRENT_VERTEX_ATTRIB = GLES3.GL_CURRENT_VERTEX_ATTRIB
CW = GLES3.GL_CW
DECR = GLES3.GL_DECR
DECR_WRAP = GLES3.GL_DECR_WRAP
DELETE_STATUS = GLES3.GL_DELETE_STATUS
DEPTH = GLES3.GL_DEPTH
DEPTH24_STENCIL8 = GLES3.GL_DEPTH24_STENCIL8
DEPTH32F_STENCIL8 = GLES3.GL_DEPTH32F_STENCIL8
DEPTH_ATTACHMENT = GLES3.GL_DEPTH_ATTACHMENT
DEPTH_BITS = GLES3.GL_DEPTH_BITS
DEPTH_BUFFER_BIT = GLES3.GL_DEPTH_BUFFER_BIT
DEPTH_CLEAR_VALUE = GLES3.GL_DEPTH_CLEAR_VALUE
DEPTH_COMPONENT = GLES3.GL_DEPTH_COMPONENT
DEPTH_COMPONENT16 = GLES3.GL_DEPTH_COMPONENT16
DEPTH_COMPONENT24 = GLES3.GL_DEPTH_COMPONENT24
DEPTH_COMPONENT32F = GLES3.GL_DEPTH_COMPONENT32F
DEPTH_FUNC = GLES3.GL_DEPTH_FUNC
DEPTH_RANGE = GLES3.GL_DEPTH_RANGE
DEPTH_STENCIL = GLES3.GL_DEPTH_STENCIL
DEPTH_STENCIL_ATTACHMENT = GLES3.GL_DEPTH_STENCIL_ATTACHMENT
DEPTH_STENCIL_TEXTURE_MODE = GLES3.GL_DEPTH_STENCIL_TEXTURE_MODE
DEPTH_TEST = GLES3.GL_DEPTH_TEST
DEPTH_WRITEMASK = GLES3.GL_DEPTH_WRITEMASK
DISPATCH_INDIRECT_BUFFER = GLES3.GL_DISPATCH_INDIRECT_BUFFER
DISPATCH_INDIRECT_BUFFER_BINDING = GLES3.GL_DISPATCH_INDIRECT_BUFFER_BINDING
DITHER = GLES3.GL_DITHER
DONT_CARE = GLES3.GL_DONT_CARE
DOUBLE = GLES3.GL_DOUBLE
DRAW_BUFFER0 = GLES3.GL_DRAW_BUFFER0
DRAW_BUFFER1 = GLES3.GL_DRAW_BUFFER1
DRAW_BUFFER10 = GLES3.GL_DRAW_BUFFER10
DRAW_BUFFER11 = GLES3.GL_DRAW_BUFFER11
DRAW_BUFFER12 = GLES3.GL_DRAW_BUFFER12
DRAW_BUFFER13 = GLES3.GL_DRAW_BUFFER13
DRAW_BUFFER14 = GLES3.GL_DRAW_BUFFER14
DRAW_BUFFER15 = GLES3.GL_DRAW_BUFFER15
DRAW_BUFFER2 = GLES3.GL_DRAW_BUFFER2
DRAW_BUFFER3 = GLES3.GL_DRAW_BUFFER3
DRAW_BUFFER4 = GLES3.GL_DRAW_BUFFER4
DRAW_BUFFER5 = GLES3.GL_DRAW_BUFFER5
DRAW_BUFFER6 = GLES3.GL_DRAW_BUFFER6
DRAW_BUFFER7 = GLES3.GL_DRAW_BUFFER7
DRAW_BUFFER8 = GLES3.GL_DRAW_BUFFER8
DRAW_BUFFER9 = GLES3.GL_DRAW_BUFFER9
DRAW_FRAMEBUFFER = GLES3.GL_DRAW_FRAMEBUFFER
DRAW_FRAMEBUFFER_BINDING = GLES3.GL_DRAW_FRAMEBUFFER_BINDING
DRAW_INDIRECT_BUFFER = GLES3.GL_DRAW_INDIRECT_BUFFER
DRAW_INDIRECT_BUFFER_BINDING = GLES3.GL_DRAW_INDIRECT_BUFFER_BINDING
DST_ALPHA = GLES3.GL_DST_ALPHA
DST_COLOR = GLES3.GL_DST_COLOR
DYNAMIC_COPY = GLES3.GL_DYNAMIC_COPY
DYNAMIC_DRAW = GLES3.GL_DYNAMIC_DRAW
DYNAMIC_READ = GLES3.GL_DYNAMIC_READ
ELEMENT_ARRAY_BARRIER_BIT = GLES3.GL_ELEMENT_ARRAY_BARRIER_BIT
ELEMENT_ARRAY_BUFFER = GLES3.GL_ELEMENT_ARRAY_BUFFER
ELEMENT_ARRAY_BUFFER_BINDING = GLES3.GL_ELEMENT_ARRAY_BUFFER_BINDING
EQUAL = GLES3.GL_EQUAL
EXTENSIONS = GLES3.GL_EXTENSIONS
FALSE = GLES3.GL_FALSE
FASTEST = GLES3.GL_FASTEST
FIXED = GLES3.GL_FIXED
FLOAT = GLES3.GL_FLOAT
FLOAT_32_UNSIGNED_INT_24_8_REV = GLES3.GL_FLOAT_32_UNSIGNED_INT_24_8_REV
FLOAT_MAT2 = GLES3.GL_FLOAT_MAT2
FLOAT_MAT2x3 = GLES3.GL_FLOAT_MAT2x3
FLOAT_MAT2x4 = GLES3.GL_FLOAT_MAT2x4
FLOAT_MAT3 = GLES3.GL_FLOAT_MAT3
FLOAT_MAT3x2 = GLES3.GL_FLOAT_MAT3x2
FLOAT_MAT3x4 = GLES3.GL_FLOAT_MAT3x4
FLOAT_MAT4 = GLES3.GL_FLOAT_MAT4
FLOAT_MAT4x2 = GLES3.GL_FLOAT_MAT4x2
FLOAT_MAT4x3 = GLES3.GL_FLOAT_MAT4x3
FLOAT_VEC2 = GLES3.GL_FLOAT_VEC2
FLOAT_VEC3 = GLES3.GL_FLOAT_VEC3
FLOAT_VEC4 = GLES3.GL_FLOAT_VEC4
FRAGMENT_SHADER = GLES3.GL_FRAGMENT_SHADER
FRAGMENT_SHADER_BIT = GLES3.GL_FRAGMENT_SHADER_BIT
FRAGMENT_SHADER_DERIVATIVE_HINT = GLES3.GL_FRAGMENT_SHADER_DERIVATIVE_HINT
FRAMEBUFFER = GLES3.GL_FRAMEBUFFER
FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE = GLES3.GL_FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE
FRAMEBUFFER_ATTACHMENT_BLUE_SIZE = GLES3.GL_FRAMEBUFFER_ATTACHMENT_BLUE_SIZE
FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING = GLES3.GL_FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING
FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE = GLES3.GL_FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE
FRAMEBUFFER_ATTACHMENT_DEPTH_SIZE = GLES3.GL_FRAMEBUFFER_ATTACHMENT_DEPTH_SIZE
FRAMEBUFFER_ATTACHMENT_GREEN_SIZE = GLES3.GL_FRAMEBUFFER_ATTACHMENT_GREEN_SIZE
FRAMEBUFFER_ATTACHMENT_OBJECT_NAME = GLES3.GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME
FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE = GLES3.GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE
FRAMEBUFFER_ATTACHMENT_RED_SIZE = GLES3.GL_FRAMEBUFFER_ATTACHMENT_RED_SIZE
FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE = GLES3.GL_FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE
FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE = GLES3.GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE
FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER = GLES3.GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER
FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL = GLES3.GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL
FRAMEBUFFER_BARRIER_BIT = GLES3.GL_FRAMEBUFFER_BARRIER_BIT
FRAMEBUFFER_BINDING = GLES3.GL_FRAMEBUFFER_BINDING
FRAMEBUFFER_COMPLETE = GLES3.GL_FRAMEBUFFER_COMPLETE
FRAMEBUFFER_DEFAULT = GLES3.GL_FRAMEBUFFER_DEFAULT
FRAMEBUFFER_DEFAULT_FIXED_SAMPLE_LOCATIONS = GLES3.GL_FRAMEBUFFER_DEFAULT_FIXED_SAMPLE_LOCATIONS
FRAMEBUFFER_DEFAULT_HEIGHT = GLES3.GL_FRAMEBUFFER_DEFAULT_HEIGHT
FRAMEBUFFER_DEFAULT_SAMPLES = GLES3.GL_FRAMEBUFFER_DEFAULT_SAMPLES
FRAMEBUFFER_DEFAULT_WIDTH = GLES3.GL_FRAMEBUFFER_DEFAULT_WIDTH
FRAMEBUFFER_INCOMPLETE_ATTACHMENT = GLES3.GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT
FRAMEBUFFER_INCOMPLETE_DIMENSIONS = GLES3.GL_FRAMEBUFFER_INCOMPLETE_DIMENSIONS
FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT = GLES3.GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT
FRAMEBUFFER_INCOMPLETE_MULTISAMPLE = GLES3.GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE
FRAMEBUFFER_UNDEFINED = GLES3.GL_FRAMEBUFFER_UNDEFINED
FRAMEBUFFER_UNSUPPORTED = GLES3.GL_FRAMEBUFFER_UNSUPPORTED
FRONT = GLES3.GL_FRONT
FRONT_AND_BACK = GLES3.GL_FRONT_AND_BACK
FRONT_FACE = GLES3.GL_FRONT_FACE
FUNC_ADD = GLES3.GL_FUNC_ADD
FUNC_REVERSE_SUBTRACT = GLES3.GL_FUNC_REVERSE_SUBTRACT
FUNC_SUBTRACT = GLES3.GL_FUNC_SUBTRACT
GENERATE_MIPMAP_HINT = GLES3.GL_GENERATE_MIPMAP_HINT
GEQUAL = GLES3.GL_GEQUAL
GREATER = GLES3.GL_GREATER
GREEN = GLES3.GL_GREEN
GREEN_BITS = GLES3.GL_GREEN_BITS
HALF_FLOAT = GLES3.GL_HALF_FLOAT
HALF_NV = GLES3.GL_HALF_NV
HIGH_FLOAT = GLES3.GL_HIGH_FLOAT
HIGH_INT = GLES3.GL_HIGH_INT
IMAGE_2D = GLES3.GL_IMAGE_2D
IMAGE_2D_ARRAY = GLES3.GL_IMAGE_2D_ARRAY
IMAGE_3D = GLES3.GL_IMAGE_3D
IMAGE_BINDING_ACCESS = GLES3.GL_IMAGE_BINDING_ACCESS
IMAGE_BINDING_FORMAT = GLES3.GL_IMAGE_BINDING_FORMAT
IMAGE_BINDING_LAYER = GLES3.GL_IMAGE_BINDING_LAYER
IMAGE_BINDING_LAYERED = GLES3.GL_IMAGE_BINDING_LAYERED
IMAGE_BINDING_LEVEL = GLES3.GL_IMAGE_BINDING_LEVEL
IMAGE_BINDING_NAME = GLES3.GL_IMAGE_BINDING_NAME
IMAGE_CUBE = GLES3.GL_IMAGE_CUBE
IMAGE_FORMAT_COMPATIBILITY_BY_CLASS = GLES3.GL_IMAGE_FORMAT_COMPATIBILITY_BY_CLASS
IMAGE_FORMAT_COMPATIBILITY_BY_SIZE = GLES3.GL_IMAGE_FORMAT_COMPATIBILITY_BY_SIZE
IMAGE_FORMAT_COMPATIBILITY_TYPE = GLES3.GL_IMAGE_FORMAT_COMPATIBILITY_TYPE
IMPLEMENTATION_COLOR_READ_FORMAT = GLES3.GL_IMPLEMENTATION_COLOR_READ_FORMAT
IMPLEMENTATION_COLOR_READ_TYPE = GLES3.GL_IMPLEMENTATION_COLOR_READ_TYPE
INCR = GLES3.GL_INCR
INCR_WRAP = GLES3.GL_INCR_WRAP
INFO_LOG_LENGTH = GLES3.GL_INFO_LOG_LENGTH
INT = GLES3.GL_INT
INTERLEAVED_ATTRIBS = GLES3.GL_INTERLEAVED_ATTRIBS
INT_2_10_10_10_REV = GLES3.GL_INT_2_10_10_10_REV
INT_IMAGE_2D = GLES3.GL_INT_IMAGE_2D
INT_IMAGE_2D_ARRAY = GLES3.GL_INT_IMAGE_2D_ARRAY
INT_IMAGE_3D = GLES3.GL_INT_IMAGE_3D
INT_IMAGE_CUBE = GLES3.GL_INT_IMAGE_CUBE
INT_SAMPLER_2D = GLES3.GL_INT_SAMPLER_2D
INT_SAMPLER_2D_ARRAY = GLES3.GL_INT_SAMPLER_2D_ARRAY
INT_SAMPLER_2D_MULTISAMPLE = GLES3.GL_INT_SAMPLER_2D_MULTISAMPLE
INT_SAMPLER_3D = GLES3.GL_INT_SAMPLER_3D
INT_SAMPLER_CUBE = GLES3.GL_INT_SAMPLER_CUBE
INT_VEC2 = GLES3.GL_INT_VEC2
INT_VEC3 = GLES3.GL_INT_VEC3
INT_VEC4 = GLES3.GL_INT_VEC4
INVALID_ENUM = GLES3.GL_INVALID_ENUM
INVALID_FRAMEBUFFER_OPERATION = GLES3.GL_INVALID_FRAMEBUFFER_OPERATION
INVALID_INDEX = GLES3.GL_INVALID_INDEX
INVALID_OPERATION = GLES3.GL_INVALID_OPERATION
INVALID_VALUE = GLES3.GL_INVALID_VALUE
INVERT = GLES3.GL_INVERT
IS_ROW_MAJOR = GLES3.GL_IS_ROW_MAJOR
KEEP = GLES3.GL_KEEP
LEQUAL = GLES3.GL_LEQUAL
LESS = GLES3.GL_LESS
LINEAR = GLES3.GL_LINEAR
LINEAR_MIPMAP_LINEAR = GLES3.GL_LINEAR_MIPMAP_LINEAR
LINEAR_MIPMAP_NEAREST = GLES3.GL_LINEAR_MIPMAP_NEAREST
LINES = GLES3.GL_LINES
LINE_LOOP = GLES3.GL_LINE_LOOP
LINE_STRIP = GLES3.GL_LINE_STRIP
LINE_WIDTH = GLES3.GL_LINE_WIDTH
LINK_STATUS = GLES3.GL_LINK_STATUS
LOCATION = GLES3.GL_LOCATION
LOW_FLOAT = GLES3.GL_LOW_FLOAT
LOW_INT = GLES3.GL_LOW_INT
LUMINANCE = GLES3.GL_LUMINANCE
LUMINANCE_ALPHA = GLES3.GL_LUMINANCE_ALPHA
MAJOR_VERSION = GLES3.GL_MAJOR_VERSION
MAP_FLUSH_EXPLICIT_BIT = GLES3.GL_MAP_FLUSH_EXPLICIT_BIT
MAP_INVALIDATE_BUFFER_BIT = GLES3.GL_MAP_INVALIDATE_BUFFER_BIT
MAP_INVALIDATE_RANGE_BIT = GLES3.GL_MAP_INVALIDATE_RANGE_BIT
MAP_READ_BIT = GLES3.GL_MAP_READ_BIT
MAP_UNSYNCHRONIZED_BIT = GLES3.GL_MAP_UNSYNCHRONIZED_BIT
MAP_WRITE_BIT = GLES3.GL_MAP_WRITE_BIT
MATRIX_STRIDE = GLES3.GL_MATRIX_STRIDE
MAX = GLES3.GL_MAX
MAX_3D_TEXTURE_SIZE = GLES3.GL_MAX_3D_TEXTURE_SIZE
MAX_ARRAY_TEXTURE_LAYERS = GLES3.GL_MAX_ARRAY_TEXTURE_LAYERS
MAX_ATOMIC_COUNTER_BUFFER_BINDINGS = GLES3.GL_MAX_ATOMIC_COUNTER_BUFFER_BINDINGS
MAX_ATOMIC_COUNTER_BUFFER_SIZE = GLES3.GL_MAX_ATOMIC_COUNTER_BUFFER_SIZE
MAX_COLOR_ATTACHMENTS = GLES3.GL_MAX_COLOR_ATTACHMENTS
MAX_COLOR_TEXTURE_SAMPLES = GLES3.GL_MAX_COLOR_TEXTURE_SAMPLES
MAX_COMBINED_ATOMIC_COUNTERS = GLES3.GL_MAX_COMBINED_ATOMIC_COUNTERS
MAX_COMBINED_ATOMIC_COUNTER_BUFFERS = GLES3.GL_MAX_COMBINED_ATOMIC_COUNTER_BUFFERS
MAX_COMBINED_COMPUTE_UNIFORM_COMPONENTS = GLES3.GL_MAX_COMBINED_COMPUTE_UNIFORM_COMPONENTS
MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS = GLES3.GL_MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS
MAX_COMBINED_IMAGE_UNIFORMS = GLES3.GL_MAX_COMBINED_IMAGE_UNIFORMS
MAX_COMBINED_SHADER_OUTPUT_RESOURCES = GLES3.GL_MAX_COMBINED_SHADER_OUTPUT_RESOURCES
MAX_COMBINED_SHADER_STORAGE_BLOCKS = GLES3.GL_MAX_COMBINED_SHADER_STORAGE_BLOCKS
MAX_COMBINED_TEXTURE_IMAGE_UNITS = GLES3.GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS
MAX_COMBINED_UNIFORM_BLOCKS = GLES3.GL_MAX_COMBINED_UNIFORM_BLOCKS
MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS = GLES3.GL_MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS
MAX_COMPUTE_ATOMIC_COUNTERS = GLES3.GL_MAX_COMPUTE_ATOMIC_COUNTERS
MAX_COMPUTE_ATOMIC_COUNTER_BUFFERS = GLES3.GL_MAX_COMPUTE_ATOMIC_COUNTER_BUFFERS
MAX_COMPUTE_IMAGE_UNIFORMS = GLES3.GL_MAX_COMPUTE_IMAGE_UNIFORMS
MAX_COMPUTE_SHADER_STORAGE_BLOCKS = GLES3.GL_MAX_COMPUTE_SHADER_STORAGE_BLOCKS
MAX_COMPUTE_SHARED_MEMORY_SIZE = GLES3.GL_MAX_COMPUTE_SHARED_MEMORY_SIZE
MAX_COMPUTE_TEXTURE_IMAGE_UNITS = GLES3.GL_MAX_COMPUTE_TEXTURE_IMAGE_UNITS
MAX_COMPUTE_UNIFORM_BLOCKS = GLES3.GL_MAX_COMPUTE_UNIFORM_BLOCKS
MAX_COMPUTE_UNIFORM_COMPONENTS = GLES3.GL_MAX_COMPUTE_UNIFORM_COMPONENTS
MAX_COMPUTE_WORK_GROUP_COUNT = GLES3.GL_MAX_COMPUTE_WORK_GROUP_COUNT
MAX_COMPUTE_WORK_GROUP_INVOCATIONS = GLES3.GL_MAX_COMPUTE_WORK_GROUP_INVOCATIONS
MAX_COMPUTE_WORK_GROUP_SIZE = GLES3.GL_MAX_COMPUTE_WORK_GROUP_SIZE
MAX_CUBE_MAP_TEXTURE_SIZE = GLES3.GL_MAX_CUBE_MAP_TEXTURE_SIZE
MAX_DEPTH_TEXTURE_SAMPLES = GLES3.GL_MAX_DEPTH_TEXTURE_SAMPLES
MAX_DRAW_BUFFERS = GLES3.GL_MAX_DRAW_BUFFERS
MAX_ELEMENTS_INDICES = GLES3.GL_MAX_ELEMENTS_INDICES
MAX_ELEMENTS_VERTICES = GLES3.GL_MAX_ELEMENTS_VERTICES
MAX_ELEMENT_INDEX = GLES3.GL_MAX_ELEMENT_INDEX
MAX_FRAGMENT_ATOMIC_COUNTERS = GLES3.GL_MAX_FRAGMENT_ATOMIC_COUNTERS
MAX_FRAGMENT_ATOMIC_COUNTER_BUFFERS = GLES3.GL_MAX_FRAGMENT_ATOMIC_COUNTER_BUFFERS
MAX_FRAGMENT_IMAGE_UNIFORMS = GLES3.GL_MAX_FRAGMENT_IMAGE_UNIFORMS
MAX_FRAGMENT_INPUT_COMPONENTS = GLES3.GL_MAX_FRAGMENT_INPUT_COMPONENTS
MAX_FRAGMENT_SHADER_STORAGE_BLOCKS = GLES3.GL_MAX_FRAGMENT_SHADER_STORAGE_BLOCKS
MAX_FRAGMENT_UNIFORM_BLOCKS = GLES3.GL_MAX_FRAGMENT_UNIFORM_BLOCKS
MAX_FRAGMENT_UNIFORM_COMPONENTS = GLES3.GL_MAX_FRAGMENT_UNIFORM_COMPONENTS
MAX_FRAGMENT_UNIFORM_VECTORS = GLES3.GL_MAX_FRAGMENT_UNIFORM_VECTORS
MAX_FRAMEBUFFER_HEIGHT = GLES3.GL_MAX_FRAMEBUFFER_HEIGHT
MAX_FRAMEBUFFER_SAMPLES = GLES3.GL_MAX_FRAMEBUFFER_SAMPLES
MAX_FRAMEBUFFER_WIDTH = GLES3.GL_MAX_FRAMEBUFFER_WIDTH
MAX_IMAGE_UNITS = GLES3.GL_MAX_IMAGE_UNITS
MAX_INTEGER_SAMPLES = GLES3.GL_MAX_INTEGER_SAMPLES
MAX_NAME_LENGTH = GLES3.GL_MAX_NAME_LENGTH
MAX_NUM_ACTIVE_VARIABLES = GLES3.GL_MAX_NUM_ACTIVE_VARIABLES
MAX_PROGRAM_TEXEL_OFFSET = GLES3.GL_MAX_PROGRAM_TEXEL_OFFSET
MAX_PROGRAM_TEXTURE_GATHER_OFFSET = GLES3.GL_MAX_PROGRAM_TEXTURE_GATHER_OFFSET
MAX_RENDERBUFFER_SIZE = GLES3.GL_MAX_RENDERBUFFER_SIZE
MAX_SAMPLES = GLES3.GL_MAX_SAMPLES
MAX_SAMPLE_MASK_WORDS = GLES3.GL_MAX_SAMPLE_MASK_WORDS
MAX_SERVER_WAIT_TIMEOUT = GLES3.GL_MAX_SERVER_WAIT_TIMEOUT
MAX_SHADER_STORAGE_BLOCK_SIZE = GLES3.GL_MAX_SHADER_STORAGE_BLOCK_SIZE
MAX_SHADER_STORAGE_BUFFER_BINDINGS = GLES3.GL_MAX_SHADER_STORAGE_BUFFER_BINDINGS
MAX_TEXTURE_IMAGE_UNITS = GLES3.GL_MAX_TEXTURE_IMAGE_UNITS
MAX_TEXTURE_LOD_BIAS = GLES3.GL_MAX_TEXTURE_LOD_BIAS
MAX_TEXTURE_SIZE = GLES3.GL_MAX_TEXTURE_SIZE
MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS = GLES3.GL_MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS
MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS = GLES3.GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS
MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS = GLES3.GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS
MAX_UNIFORM_BLOCK_SIZE = GLES3.GL_MAX_UNIFORM_BLOCK_SIZE
MAX_UNIFORM_BUFFER_BINDINGS = GLES3.GL_MAX_UNIFORM_BUFFER_BINDINGS
MAX_UNIFORM_LOCATIONS = GLES3.GL_MAX_UNIFORM_LOCATIONS
MAX_VARYING_COMPONENTS = GLES3.GL_MAX_VARYING_COMPONENTS
MAX_VARYING_VECTORS = GLES3.GL_MAX_VARYING_VECTORS
MAX_VERTEX_ATOMIC_COUNTERS = GLES3.GL_MAX_VERTEX_ATOMIC_COUNTERS
MAX_VERTEX_ATOMIC_COUNTER_BUFFERS = GLES3.GL_MAX_VERTEX_ATOMIC_COUNTER_BUFFERS
MAX_VERTEX_ATTRIBS = GLES3.GL_MAX_VERTEX_ATTRIBS
MAX_VERTEX_ATTRIB_BINDINGS = GLES3.GL_MAX_VERTEX_ATTRIB_BINDINGS
MAX_VERTEX_ATTRIB_RELATIVE_OFFSET = GLES3.GL_MAX_VERTEX_ATTRIB_RELATIVE_OFFSET
MAX_VERTEX_ATTRIB_STRIDE = GLES3.GL_MAX_VERTEX_ATTRIB_STRIDE
MAX_VERTEX_IMAGE_UNIFORMS = GLES3.GL_MAX_VERTEX_IMAGE_UNIFORMS
MAX_VERTEX_OUTPUT_COMPONENTS = GLES3.GL_MAX_VERTEX_OUTPUT_COMPONENTS
MAX_VERTEX_SHADER_STORAGE_BLOCKS = GLES3.GL_MAX_VERTEX_SHADER_STORAGE_BLOCKS
MAX_VERTEX_TEXTURE_IMAGE_UNITS = GLES3.GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS
MAX_VERTEX_UNIFORM_BLOCKS = GLES3.GL_MAX_VERTEX_UNIFORM_BLOCKS
MAX_VERTEX_UNIFORM_COMPONENTS = GLES3.GL_MAX_VERTEX_UNIFORM_COMPONENTS
MAX_VERTEX_UNIFORM_VECTORS = GLES3.GL_MAX_VERTEX_UNIFORM_VECTORS
MAX_VIEWPORT_DIMS = GLES3.GL_MAX_VIEWPORT_DIMS
MEDIUM_FLOAT = GLES3.GL_MEDIUM_FLOAT
MEDIUM_INT = GLES3.GL_MEDIUM_INT
MIN = GLES3.GL_MIN
MINOR_VERSION = GLES3.GL_MINOR_VERSION
MIN_PROGRAM_TEXEL_OFFSET = GLES3.GL_MIN_PROGRAM_TEXEL_OFFSET
MIN_PROGRAM_TEXTURE_GATHER_OFFSET = GLES3.GL_MIN_PROGRAM_TEXTURE_GATHER_OFFSET
MIRRORED_REPEAT = GLES3.GL_MIRRORED_REPEAT
NAME_LENGTH = GLES3.GL_NAME_LENGTH
NEAREST = GLES3.GL_NEAREST
NEAREST_MIPMAP_LINEAR = GLES3.GL_NEAREST_MIPMAP_LINEAR
NEAREST_MIPMAP_NEAREST = GLES3.GL_NEAREST_MIPMAP_NEAREST
NEVER = GLES3.GL_NEVER
NICEST = GLES3.GL_NICEST
NONE = GLES3.GL_NONE
NOTEQUAL = GLES3.GL_NOTEQUAL
NO_ERROR = GLES3.GL_NO_ERROR
NUM_ACTIVE_VARIABLES = GLES3.GL_NUM_ACTIVE_VARIABLES
NUM_COMPRESSED_TEXTURE_FORMATS = GLES3.GL_NUM_COMPRESSED_TEXTURE_FORMATS
NUM_EXTENSIONS = GLES3.GL_NUM_EXTENSIONS
NUM_PROGRAM_BINARY_FORMATS = GLES3.GL_NUM_PROGRAM_BINARY_FORMATS
NUM_SAMPLE_COUNTS = GLES3.GL_NUM_SAMPLE_COUNTS
NUM_SHADER_BINARY_FORMATS = GLES3.GL_NUM_SHADER_BINARY_FORMATS
OBJECT_TYPE = GLES3.GL_OBJECT_TYPE
OFFSET = GLES3.GL_OFFSET
ONE = GLES3.GL_ONE
ONE_MINUS_CONSTANT_ALPHA = GLES3.GL_ONE_MINUS_CONSTANT_ALPHA
ONE_MINUS_CONSTANT_COLOR = GLES3.GL_ONE_MINUS_CONSTANT_COLOR
ONE_MINUS_DST_ALPHA = GLES3.GL_ONE_MINUS_DST_ALPHA
ONE_MINUS_DST_COLOR = GLES3.GL_ONE_MINUS_DST_COLOR
ONE_MINUS_SRC_ALPHA = GLES3.GL_ONE_MINUS_SRC_ALPHA
ONE_MINUS_SRC_COLOR = GLES3.GL_ONE_MINUS_SRC_COLOR
OUT_OF_MEMORY = GLES3.GL_OUT_OF_MEMORY
PACK_ALIGNMENT = GLES3.GL_PACK_ALIGNMENT
PACK_ROW_LENGTH = GLES3.GL_PACK_ROW_LENGTH
PACK_SKIP_PIXELS = GLES3.GL_PACK_SKIP_PIXELS
PACK_SKIP_ROWS = GLES3.GL_PACK_SKIP_ROWS
PIXEL_BUFFER_BARRIER_BIT = GLES3.GL_PIXEL_BUFFER_BARRIER_BIT
PIXEL_PACK_BUFFER = GLES3.GL_PIXEL_PACK_BUFFER
PIXEL_PACK_BUFFER_BINDING = GLES3.GL_PIXEL_PACK_BUFFER_BINDING
PIXEL_UNPACK_BUFFER = GLES3.GL_PIXEL_UNPACK_BUFFER
PIXEL_UNPACK_BUFFER_BINDING = GLES3.GL_PIXEL_UNPACK_BUFFER_BINDING
POINTS = GLES3.GL_POINTS
POLYGON_OFFSET_FACTOR = GLES3.GL_POLYGON_OFFSET_FACTOR
POLYGON_OFFSET_FILL = GLES3.GL_POLYGON_OFFSET_FILL
POLYGON_OFFSET_UNITS = GLES3.GL_POLYGON_OFFSET_UNITS
PRIMITIVE_RESTART_FIXED_INDEX = GLES3.GL_PRIMITIVE_RESTART_FIXED_INDEX
PROGRAM_BINARY_FORMATS = GLES3.GL_PROGRAM_BINARY_FORMATS
PROGRAM_BINARY_LENGTH = GLES3.GL_PROGRAM_BINARY_LENGTH
PROGRAM_BINARY_RETRIEVABLE_HINT = GLES3.GL_PROGRAM_BINARY_RETRIEVABLE_HINT
PROGRAM_INPUT = GLES3.GL_PROGRAM_INPUT
PROGRAM_OUTPUT = GLES3.GL_PROGRAM_OUTPUT
PROGRAM_PIPELINE_BINDING = GLES3.GL_PROGRAM_PIPELINE_BINDING
PROGRAM_SEPARABLE = GLES3.GL_PROGRAM_SEPARABLE
QUERY_RESULT = GLES3.GL_QUERY_RESULT
QUERY_RESULT_AVAILABLE = GLES3.GL_QUERY_RESULT_AVAILABLE
R11F_G11F_B10F = GLES3.GL_R11F_G11F_B10F
R16F = GLES3.GL_R16F
R16I = GLES3.GL_R16I
R16UI = GLES3.GL_R16UI
R32F = GLES3.GL_R32F
R32I = GLES3.GL_R32I
R32UI = GLES3.GL_R32UI
R8 = GLES3.GL_R8
R8I = GLES3.GL_R8I
R8UI = GLES3.GL_R8UI
R8_SNORM = GLES3.GL_R8_SNORM
RASTERIZER_DISCARD = GLES3.GL_RASTERIZER_DISCARD
READ_BUFFER = GLES3.GL_READ_BUFFER
READ_FRAMEBUFFER = GLES3.GL_READ_FRAMEBUFFER
READ_FRAMEBUFFER_BINDING = GLES3.GL_READ_FRAMEBUFFER_BINDING
READ_ONLY = GLES3.GL_READ_ONLY
READ_WRITE = GLES3.GL_READ_WRITE
RED = GLES3.GL_RED
RED_BITS = GLES3.GL_RED_BITS
RED_INTEGER = GLES3.GL_RED_INTEGER
REFERENCED_BY_COMPUTE_SHADER = GLES3.GL_REFERENCED_BY_COMPUTE_SHADER
REFERENCED_BY_FRAGMENT_SHADER = GLES3.GL_REFERENCED_BY_FRAGMENT_SHADER
REFERENCED_BY_VERTEX_SHADER = GLES3.GL_REFERENCED_BY_VERTEX_SHADER
RENDERBUFFER = GLES3.GL_RENDERBUFFER
RENDERBUFFER_ALPHA_SIZE = GLES3.GL_RENDERBUFFER_ALPHA_SIZE
RENDERBUFFER_BINDING = GLES3.GL_RENDERBUFFER_BINDING
RENDERBUFFER_BLUE_SIZE = GLES3.GL_RENDERBUFFER_BLUE_SIZE
RENDERBUFFER_DEPTH_SIZE = GLES3.GL_RENDERBUFFER_DEPTH_SIZE
RENDERBUFFER_GREEN_SIZE = GLES3.GL_RENDERBUFFER_GREEN_SIZE
RENDERBUFFER_HEIGHT = GLES3.GL_RENDERBUFFER_HEIGHT
RENDERBUFFER_INTERNAL_FORMAT = GLES3.GL_RENDERBUFFER_INTERNAL_FORMAT
RENDERBUFFER_RED_SIZE = GLES3.GL_RENDERBUFFER_RED_SIZE
RENDERBUFFER_SAMPLES = GLES3.GL_RENDERBUFFER_SAMPLES
RENDERBUFFER_STENCIL_SIZE = GLES3.GL_RENDERBUFFER_STENCIL_SIZE
RENDERBUFFER_WIDTH = GLES3.GL_RENDERBUFFER_WIDTH
RENDERER = GLES3.GL_RENDERER
REPEAT = GLES3.GL_REPEAT
REPLACE = GLES3.GL_REPLACE
RG = GLES3.GL_RG
RG16F = GLES3.GL_RG16F
RG16I = GLES3.GL_RG16I
RG16UI = GLES3.GL_RG16UI
RG32F = GLES3.GL_RG32F
RG32I = GLES3.GL_RG32I
RG32UI = GLES3.GL_RG32UI
RG8 = GLES3.GL_RG8
RG8I = GLES3.GL_RG8I
RG8UI = GLES3.GL_RG8UI
RG8_SNORM = GLES3.GL_RG8_SNORM
RGB = GLES3.GL_RGB
RGB10_A2 = GLES3.GL_RGB10_A2
RGB10_A2UI = GLES3.GL_RGB10_A2UI
RGB16F = GLES3.GL_RGB16F
RGB16I = GLES3.GL_RGB16I
RGB16UI = GLES3.GL_RGB16UI
RGB32F = GLES3.GL_RGB32F
RGB32I = GLES3.GL_RGB32I
RGB32UI = GLES3.GL_RGB32UI
RGB565 = GLES3.GL_RGB565
RGB5_A1 = GLES3.GL_RGB5_A1
RGB8 = GLES3.GL_RGB8
RGB8I = GLES3.GL_RGB8I
RGB8UI = GLES3.GL_RGB8UI
RGB8_SNORM = GLES3.GL_RGB8_SNORM
RGB9_E5 = GLES3.GL_RGB9_E5
RGBA = GLES3.GL_RGBA
RGBA16F = GLES3.GL_RGBA16F
RGBA16I = GLES3.GL_RGBA16I
RGBA16UI = GLES3.GL_RGBA16UI
RGBA32F = GLES3.GL_RGBA32F
RGBA32I = GLES3.GL_RGBA32I
RGBA32UI = GLES3.GL_RGBA32UI
RGBA4 = GLES3.GL_RGBA4
RGBA8 = GLES3.GL_RGBA8
RGBA8I = GLES3.GL_RGBA8I
RGBA8UI = GLES3.GL_RGBA8UI
RGBA8_SNORM = GLES3.GL_RGBA8_SNORM
RGBA_INTEGER = GLES3.GL_RGBA_INTEGER
RGB_INTEGER = GLES3.GL_RGB_INTEGER
RG_INTEGER = GLES3.GL_RG_INTEGER
SAMPLER_2D = GLES3.GL_SAMPLER_2D
SAMPLER_2D_ARRAY = GLES3.GL_SAMPLER_2D_ARRAY
SAMPLER_2D_ARRAY_SHADOW = GLES3.GL_SAMPLER_2D_ARRAY_SHADOW
SAMPLER_2D_MULTISAMPLE = GLES3.GL_SAMPLER_2D_MULTISAMPLE
SAMPLER_2D_SHADOW = GLES3.GL_SAMPLER_2D_SHADOW
SAMPLER_3D = GLES3.GL_SAMPLER_3D
SAMPLER_BINDING = GLES3.GL_SAMPLER_BINDING
SAMPLER_CUBE = GLES3.GL_SAMPLER_CUBE
SAMPLER_CUBE_SHADOW = GLES3.GL_SAMPLER_CUBE_SHADOW
SAMPLES = GLES3.GL_SAMPLES
SAMPLE_ALPHA_TO_COVERAGE = GLES3.GL_SAMPLE_ALPHA_TO_COVERAGE
SAMPLE_BUFFERS = GLES3.GL_SAMPLE_BUFFERS
SAMPLE_COVERAGE = GLES3.GL_SAMPLE_COVERAGE
SAMPLE_COVERAGE_INVERT = GLES3.GL_SAMPLE_COVERAGE_INVERT
SAMPLE_COVERAGE_VALUE = GLES3.GL_SAMPLE_COVERAGE_VALUE
SAMPLE_MASK = GLES3.GL_SAMPLE_MASK
SAMPLE_MASK_VALUE = GLES3.GL_SAMPLE_MASK_VALUE
SAMPLE_POSITION = GLES3.GL_SAMPLE_POSITION
SCISSOR_BOX = GLES3.GL_SCISSOR_BOX
SCISSOR_TEST = GLES3.GL_SCISSOR_TEST
SEPARATE_ATTRIBS = GLES3.GL_SEPARATE_ATTRIBS
SHADER_BINARY_FORMATS = GLES3.GL_SHADER_BINARY_FORMATS
SHADER_COMPILER = GLES3.GL_SHADER_COMPILER
SHADER_IMAGE_ACCESS_BARRIER_BIT = GLES3.GL_SHADER_IMAGE_ACCESS_BARRIER_BIT
SHADER_SOURCE_LENGTH = GLES3.GL_SHADER_SOURCE_LENGTH
SHADER_STORAGE_BARRIER_BIT = GLES3.GL_SHADER_STORAGE_BARRIER_BIT
SHADER_STORAGE_BLOCK = GLES3.GL_SHADER_STORAGE_BLOCK
SHADER_STORAGE_BUFFER = GLES3.GL_SHADER_STORAGE_BUFFER
SHADER_STORAGE_BUFFER_BINDING = GLES3.GL_SHADER_STORAGE_BUFFER_BINDING
SHADER_STORAGE_BUFFER_OFFSET_ALIGNMENT = GLES3.GL_SHADER_STORAGE_BUFFER_OFFSET_ALIGNMENT
SHADER_STORAGE_BUFFER_SIZE = GLES3.GL_SHADER_STORAGE_BUFFER_SIZE
SHADER_STORAGE_BUFFER_START = GLES3.GL_SHADER_STORAGE_BUFFER_START
SHADER_TYPE = GLES3.GL_SHADER_TYPE
SHADING_LANGUAGE_VERSION = GLES3.GL_SHADING_LANGUAGE_VERSION
SHORT = GLES3.GL_SHORT
SIGNALED = GLES3.GL_SIGNALED
SIGNED_NORMALIZED = GLES3.GL_SIGNED_NORMALIZED
SRC_ALPHA = GLES3.GL_SRC_ALPHA
SRC_ALPHA_SATURATE = GLES3.GL_SRC_ALPHA_SATURATE
SRC_COLOR = GLES3.GL_SRC_COLOR
SRGB = GLES3.GL_SRGB
SRGB8 = GLES3.GL_SRGB8
SRGB8_ALPHA8 = GLES3.GL_SRGB8_ALPHA8
STATIC_COPY = GLES3.GL_STATIC_COPY
STATIC_DRAW = GLES3.GL_STATIC_DRAW
STATIC_READ = GLES3.GL_STATIC_READ
STENCIL = GLES3.GL_STENCIL
STENCIL_ATTACHMENT = GLES3.GL_STENCIL_ATTACHMENT
STENCIL_BACK_FAIL = GLES3.GL_STENCIL_BACK_FAIL
STENCIL_BACK_FUNC = GLES3.GL_STENCIL_BACK_FUNC
STENCIL_BACK_PASS_DEPTH_FAIL = GLES3.GL_STENCIL_BACK_PASS_DEPTH_FAIL
STENCIL_BACK_PASS_DEPTH_PASS = GLES3.GL_STENCIL_BACK_PASS_DEPTH_PASS
STENCIL_BACK_REF = GLES3.GL_STENCIL_BACK_REF
STENCIL_BACK_VALUE_MASK = GLES3.GL_STENCIL_BACK_VALUE_MASK
STENCIL_BACK_WRITEMASK = GLES3.GL_STENCIL_BACK_WRITEMASK
STENCIL_BITS = GLES3.GL_STENCIL_BITS
STENCIL_BUFFER_BIT = GLES3.GL_STENCIL_BUFFER_BIT
STENCIL_CLEAR_VALUE = GLES3.GL_STENCIL_CLEAR_VALUE
STENCIL_FAIL = GLES3.GL_STENCIL_FAIL
STENCIL_FUNC = GLES3.GL_STENCIL_FUNC
STENCIL_INDEX = GLES3.GL_STENCIL_INDEX
STENCIL_INDEX8 = GLES3.GL_STENCIL_INDEX8
STENCIL_PASS_DEPTH_FAIL = GLES3.GL_STENCIL_PASS_DEPTH_FAIL
STENCIL_PASS_DEPTH_PASS = GLES3.GL_STENCIL_PASS_DEPTH_PASS
STENCIL_REF = GLES3.GL_STENCIL_REF
STENCIL_TEST = GLES3.GL_STENCIL_TEST
STENCIL_VALUE_MASK = GLES3.GL_STENCIL_VALUE_MASK
STENCIL_WRITEMASK = GLES3.GL_STENCIL_WRITEMASK
STREAM_COPY = GLES3.GL_STREAM_COPY
STREAM_DRAW = GLES3.GL_STREAM_DRAW
STREAM_READ = GLES3.GL_STREAM_READ
SUBPIXEL_BITS = GLES3.GL_SUBPIXEL_BITS
SYNC_CONDITION = GLES3.GL_SYNC_CONDITION
SYNC_FENCE = GLES3.GL_SYNC_FENCE
SYNC_FLAGS = GLES3.GL_SYNC_FLAGS
SYNC_FLUSH_COMMANDS_BIT = GLES3.GL_SYNC_FLUSH_COMMANDS_BIT
SYNC_GPU_COMMANDS_COMPLETE = GLES3.GL_SYNC_GPU_COMMANDS_COMPLETE
SYNC_STATUS = GLES3.GL_SYNC_STATUS
TEXTURE = GLES3.GL_TEXTURE
TEXTURE0 = GLES3.GL_TEXTURE0
TEXTURE1 = GLES3.GL_TEXTURE1
TEXTURE10 = GLES3.GL_TEXTURE10
TEXTURE11 = GLES3.GL_TEXTURE11
TEXTURE12 = GLES3.GL_TEXTURE12
TEXTURE13 = GLES3.GL_TEXTURE13
TEXTURE14 = GLES3.GL_TEXTURE14
TEXTURE15 = GLES3.GL_TEXTURE15
TEXTURE16 = GLES3.GL_TEXTURE16
TEXTURE17 = GLES3.GL_TEXTURE17
TEXTURE18 = GLES3.GL_TEXTURE18
TEXTURE19 = GLES3.GL_TEXTURE19
TEXTURE2 = GLES3.GL_TEXTURE2
TEXTURE20 = GLES3.GL_TEXTURE20
TEXTURE21 = GLES3.GL_TEXTURE21
TEXTURE22 = GLES3.GL_TEXTURE22
TEXTURE23 = GLES3.GL_TEXTURE23
TEXTURE24 = GLES3.GL_TEXTURE24
TEXTURE25 = GLES3.GL_TEXTURE25
TEXTURE26 = GLES3.GL_TEXTURE26
TEXTURE27 = GLES3.GL_TEXTURE27
TEXTURE28 = GLES3.GL_TEXTURE28
TEXTURE29 = GLES3.GL_TEXTURE29
TEXTURE3 = GLES3.GL_TEXTURE3
TEXTURE30 = GLES3.GL_TEXTURE30
TEXTURE31 = GLES3.GL_TEXTURE31
TEXTURE4 = GLES3.GL_TEXTURE4
TEXTURE5 = GLES3.GL_TEXTURE5
TEXTURE6 = GLES3.GL_TEXTURE6
TEXTURE7 = GLES3.GL_TEXTURE7
TEXTURE8 = GLES3.GL_TEXTURE8
TEXTURE9 = GLES3.GL_TEXTURE9
TEXTURE_2D = GLES3.GL_TEXTURE_2D
TEXTURE_2D_ARRAY = GLES3.GL_TEXTURE_2D_ARRAY
TEXTURE_2D_MULTISAMPLE = GLES3.GL_TEXTURE_2D_MULTISAMPLE
TEXTURE_3D = GLES3.GL_TEXTURE_3D
TEXTURE_ALPHA_SIZE = GLES3.GL_TEXTURE_ALPHA_SIZE
TEXTURE_ALPHA_TYPE = GLES3.GL_TEXTURE_ALPHA_TYPE
TEXTURE_BASE_LEVEL = GLES3.GL_TEXTURE_BASE_LEVEL
TEXTURE_BINDING_2D = GLES3.GL_TEXTURE_BINDING_2D
TEXTURE_BINDING_2D_ARRAY = GLES3.GL_TEXTURE_BINDING_2D_ARRAY
TEXTURE_BINDING_2D_MULTISAMPLE = GLES3.GL_TEXTURE_BINDING_2D_MULTISAMPLE
TEXTURE_BINDING_3D = GLES3.GL_TEXTURE_BINDING_3D
TEXTURE_BINDING_CUBE_MAP = GLES3.GL_TEXTURE_BINDING_CUBE_MAP
TEXTURE_BLUE_SIZE = GLES3.GL_TEXTURE_BLUE_SIZE
TEXTURE_BLUE_TYPE = GLES3.GL_TEXTURE_BLUE_TYPE
TEXTURE_COMPARE_FUNC = GLES3.GL_TEXTURE_COMPARE_FUNC
TEXTURE_COMPARE_MODE = GLES3.GL_TEXTURE_COMPARE_MODE
TEXTURE_COMPRESSED = GLES3.GL_TEXTURE_COMPRESSED
TEXTURE_CUBE_MAP = GLES3.GL_TEXTURE_CUBE_MAP
TEXTURE_CUBE_MAP_NEGATIVE_X = GLES3.GL_TEXTURE_CUBE_MAP_NEGATIVE_X
TEXTURE_CUBE_MAP_NEGATIVE_Y = GLES3.GL_TEXTURE_CUBE_MAP_NEGATIVE_Y
TEXTURE_CUBE_MAP_NEGATIVE_Z = GLES3.GL_TEXTURE_CUBE_MAP_NEGATIVE_Z
TEXTURE_CUBE_MAP_POSITIVE_X = GLES3.GL_TEXTURE_CUBE_MAP_POSITIVE_X
TEXTURE_CUBE_MAP_POSITIVE_Y = GLES3.GL_TEXTURE_CUBE_MAP_POSITIVE_Y
TEXTURE_CUBE_MAP_POSITIVE_Z = GLES3.GL_TEXTURE_CUBE_MAP_POSITIVE_Z
TEXTURE_DEPTH = GLES3.GL_TEXTURE_DEPTH
TEXTURE_DEPTH_SIZE = GLES3.GL_TEXTURE_DEPTH_SIZE
TEXTURE_DEPTH_TYPE = GLES3.GL_TEXTURE_DEPTH_TYPE
TEXTURE_FETCH_BARRIER_BIT = GLES3.GL_TEXTURE_FETCH_BARRIER_BIT
TEXTURE_FIXED_SAMPLE_LOCATIONS = GLES3.GL_TEXTURE_FIXED_SAMPLE_LOCATIONS
TEXTURE_GREEN_SIZE = GLES3.GL_TEXTURE_GREEN_SIZE
TEXTURE_GREEN_TYPE = GLES3.GL_TEXTURE_GREEN_TYPE
TEXTURE_HEIGHT = GLES3.GL_TEXTURE_HEIGHT
TEXTURE_IMMUTABLE_FORMAT = GLES3.GL_TEXTURE_IMMUTABLE_FORMAT
TEXTURE_IMMUTABLE_LEVELS = GLES3.GL_TEXTURE_IMMUTABLE_LEVELS
TEXTURE_INTERNAL_FORMAT = GLES3.GL_TEXTURE_INTERNAL_FORMAT
TEXTURE_MAG_FILTER = GLES3.GL_TEXTURE_MAG_FILTER
TEXTURE_MAX_LEVEL = GLES3.GL_TEXTURE_MAX_LEVEL
TEXTURE_MAX_LOD = GLES3.GL_TEXTURE_MAX_LOD
TEXTURE_MIN_FILTER = GLES3.GL_TEXTURE_MIN_FILTER
TEXTURE_MIN_LOD = GLES3.GL_TEXTURE_MIN_LOD
TEXTURE_RED_SIZE = GLES3.GL_TEXTURE_RED_SIZE
TEXTURE_RED_TYPE = GLES3.GL_TEXTURE_RED_TYPE
TEXTURE_SAMPLES = GLES3.GL_TEXTURE_SAMPLES
TEXTURE_SHARED_SIZE = GLES3.GL_TEXTURE_SHARED_SIZE
TEXTURE_STENCIL_SIZE = GLES3.GL_TEXTURE_STENCIL_SIZE
TEXTURE_SWIZZLE_A = GLES3.GL_TEXTURE_SWIZZLE_A
TEXTURE_SWIZZLE_B = GLES3.GL_TEXTURE_SWIZZLE_B
TEXTURE_SWIZZLE_G = GLES3.GL_TEXTURE_SWIZZLE_G
TEXTURE_SWIZZLE_R = GLES3.GL_TEXTURE_SWIZZLE_R
TEXTURE_UPDATE_BARRIER_BIT = GLES3.GL_TEXTURE_UPDATE_BARRIER_BIT
TEXTURE_WIDTH = GLES3.GL_TEXTURE_WIDTH
TEXTURE_WRAP_R = GLES3.GL_TEXTURE_WRAP_R
TEXTURE_WRAP_S = GLES3.GL_TEXTURE_WRAP_S
TEXTURE_WRAP_T = GLES3.GL_TEXTURE_WRAP_T
TIMEOUT_EXPIRED = GLES3.GL_TIMEOUT_EXPIRED
TIMEOUT_IGNORED = GLES3.GL_TIMEOUT_IGNORED
TOP_LEVEL_ARRAY_SIZE = GLES3.GL_TOP_LEVEL_ARRAY_SIZE
TOP_LEVEL_ARRAY_STRIDE = GLES3.GL_TOP_LEVEL_ARRAY_STRIDE
TRANSFORM_FEEDBACK = GLES3.GL_TRANSFORM_FEEDBACK
TRANSFORM_FEEDBACK_ACTIVE = GLES3.GL_TRANSFORM_FEEDBACK_ACTIVE
TRANSFORM_FEEDBACK_BARRIER_BIT = GLES3.GL_TRANSFORM_FEEDBACK_BARRIER_BIT
TRANSFORM_FEEDBACK_BINDING = GLES3.GL_TRANSFORM_FEEDBACK_BINDING
TRANSFORM_FEEDBACK_BUFFER = GLES3.GL_TRANSFORM_FEEDBACK_BUFFER
TRANSFORM_FEEDBACK_BUFFER_BINDING = GLES3.GL_TRANSFORM_FEEDBACK_BUFFER_BINDING
TRANSFORM_FEEDBACK_BUFFER_MODE = GLES3.GL_TRANSFORM_FEEDBACK_BUFFER_MODE
TRANSFORM_FEEDBACK_BUFFER_SIZE = GLES3.GL_TRANSFORM_FEEDBACK_BUFFER_SIZE
TRANSFORM_FEEDBACK_BUFFER_START = GLES3.GL_TRANSFORM_FEEDBACK_BUFFER_START
TRANSFORM_FEEDBACK_PAUSED = GLES3.GL_TRANSFORM_FEEDBACK_PAUSED
TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN = GLES3.GL_TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN
TRANSFORM_FEEDBACK_VARYING = GLES3.GL_TRANSFORM_FEEDBACK_VARYING
TRANSFORM_FEEDBACK_VARYINGS = GLES3.GL_TRANSFORM_FEEDBACK_VARYINGS
TRANSFORM_FEEDBACK_VARYING_MAX_LENGTH = GLES3.GL_TRANSFORM_FEEDBACK_VARYING_MAX_LENGTH
TRIANGLES = GLES3.GL_TRIANGLES
TRIANGLE_FAN = GLES3.GL_TRIANGLE_FAN
TRIANGLE_STRIP = GLES3.GL_TRIANGLE_STRIP
TRUE = GLES3.GL_TRUE
TYPE = GLES3.GL_TYPE
UNIFORM = GLES3.GL_UNIFORM
UNIFORM_ARRAY_STRIDE = GLES3.GL_UNIFORM_ARRAY_STRIDE
UNIFORM_BARRIER_BIT = GLES3.GL_UNIFORM_BARRIER_BIT
UNIFORM_BLOCK = GLES3.GL_UNIFORM_BLOCK
UNIFORM_BLOCK_ACTIVE_UNIFORMS = GLES3.GL_UNIFORM_BLOCK_ACTIVE_UNIFORMS
UNIFORM_BLOCK_ACTIVE_UNIFORM_INDICES = GLES3.GL_UNIFORM_BLOCK_ACTIVE_UNIFORM_INDICES
UNIFORM_BLOCK_BINDING = GLES3.GL_UNIFORM_BLOCK_BINDING
UNIFORM_BLOCK_DATA_SIZE = GLES3.GL_UNIFORM_BLOCK_DATA_SIZE
UNIFORM_BLOCK_INDEX = GLES3.GL_UNIFORM_BLOCK_INDEX
UNIFORM_BLOCK_NAME_LENGTH = GLES3.GL_UNIFORM_BLOCK_NAME_LENGTH
UNIFORM_BLOCK_REFERENCED_BY_FRAGMENT_SHADER = GLES3.GL_UNIFORM_BLOCK_REFERENCED_BY_FRAGMENT_SHADER
UNIFORM_BLOCK_REFERENCED_BY_VERTEX_SHADER = GLES3.GL_UNIFORM_BLOCK_REFERENCED_BY_VERTEX_SHADER
UNIFORM_BUFFER = GLES3.GL_UNIFORM_BUFFER
UNIFORM_BUFFER_BINDING = GLES3.GL_UNIFORM_BUFFER_BINDING
UNIFORM_BUFFER_OFFSET_ALIGNMENT = GLES3.GL_UNIFORM_BUFFER_OFFSET_ALIGNMENT
UNIFORM_BUFFER_SIZE = GLES3.GL_UNIFORM_BUFFER_SIZE
UNIFORM_BUFFER_START = GLES3.GL_UNIFORM_BUFFER_START
UNIFORM_IS_ROW_MAJOR = GLES3.GL_UNIFORM_IS_ROW_MAJOR
UNIFORM_MATRIX_STRIDE = GLES3.GL_UNIFORM_MATRIX_STRIDE
UNIFORM_NAME_LENGTH = GLES3.GL_UNIFORM_NAME_LENGTH
UNIFORM_OFFSET = GLES3.GL_UNIFORM_OFFSET
UNIFORM_SIZE = GLES3.GL_UNIFORM_SIZE
UNIFORM_TYPE = GLES3.GL_UNIFORM_TYPE
UNPACK_ALIGNMENT = GLES3.GL_UNPACK_ALIGNMENT
UNPACK_IMAGE_HEIGHT = GLES3.GL_UNPACK_IMAGE_HEIGHT
UNPACK_ROW_LENGTH = GLES3.GL_UNPACK_ROW_LENGTH
UNPACK_SKIP_IMAGES = GLES3.GL_UNPACK_SKIP_IMAGES
UNPACK_SKIP_PIXELS = GLES3.GL_UNPACK_SKIP_PIXELS
UNPACK_SKIP_ROWS = GLES3.GL_UNPACK_SKIP_ROWS
UNSIGNALED = GLES3.GL_UNSIGNALED
UNSIGNED_BYTE = GLES3.GL_UNSIGNED_BYTE
UNSIGNED_INT = GLES3.GL_UNSIGNED_INT
UNSIGNED_INT64 = GLES3.GL_UNSIGNED_INT64
UNSIGNED_INT_10F_11F_11F_REV = GLES3.GL_UNSIGNED_INT_10F_11F_11F_REV
UNSIGNED_INT_24_8 = GLES3.GL_UNSIGNED_INT_24_8
UNSIGNED_INT_2_10_10_10_REV = GLES3.GL_UNSIGNED_INT_2_10_10_10_REV
UNSIGNED_INT_5_9_9_9_REV = GLES3.GL_UNSIGNED_INT_5_9_9_9_REV
UNSIGNED_INT_ATOMIC_COUNTER = GLES3.GL_UNSIGNED_INT_ATOMIC_COUNTER
UNSIGNED_INT_IMAGE_2D = GLES3.GL_UNSIGNED_INT_IMAGE_2D
UNSIGNED_INT_IMAGE_2D_ARRAY = GLES3.GL_UNSIGNED_INT_IMAGE_2D_ARRAY
UNSIGNED_INT_IMAGE_3D = GLES3.GL_UNSIGNED_INT_IMAGE_3D
UNSIGNED_INT_IMAGE_CUBE = GLES3.GL_UNSIGNED_INT_IMAGE_CUBE
UNSIGNED_INT_SAMPLER_2D = GLES3.GL_UNSIGNED_INT_SAMPLER_2D
UNSIGNED_INT_SAMPLER_2D_ARRAY = GLES3.GL_UNSIGNED_INT_SAMPLER_2D_ARRAY
UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE = GLES3.GL_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE
UNSIGNED_INT_SAMPLER_3D = GLES3.GL_UNSIGNED_INT_SAMPLER_3D
UNSIGNED_INT_SAMPLER_CUBE = GLES3.GL_UNSIGNED_INT_SAMPLER_CUBE
UNSIGNED_INT_VEC2 = GLES3.GL_UNSIGNED_INT_VEC2
UNSIGNED_INT_VEC3 = GLES3.GL_UNSIGNED_INT_VEC3
UNSIGNED_INT_VEC4 = GLES3.GL_UNSIGNED_INT_VEC4
UNSIGNED_NORMALIZED = GLES3.GL_UNSIGNED_NORMALIZED
UNSIGNED_SHORT = GLES3.GL_UNSIGNED_SHORT
UNSIGNED_SHORT_4_4_4_4 = GLES3.GL_UNSIGNED_SHORT_4_4_4_4
UNSIGNED_SHORT_5_5_5_1 = GLES3.GL_UNSIGNED_SHORT_5_5_5_1
UNSIGNED_SHORT_5_6_5 = GLES3.GL_UNSIGNED_SHORT_5_6_5
VALIDATE_STATUS = GLES3.GL_VALIDATE_STATUS
VENDOR = GLES3.GL_VENDOR
VERSION = GLES3.VERSION
VERTEX_ARRAY_BINDING = GLES3.GL_VERTEX_ARRAY_BINDING
VERTEX_ATTRIB_ARRAY_BARRIER_BIT = GLES3.GL_VERTEX_ATTRIB_ARRAY_BARRIER_BIT
VERTEX_ATTRIB_ARRAY_BUFFER_BINDING = GLES3.GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING
VERTEX_ATTRIB_ARRAY_DIVISOR = GLES3.GL_VERTEX_ATTRIB_ARRAY_DIVISOR
VERTEX_ATTRIB_ARRAY_ENABLED = GLES3.GL_VERTEX_ATTRIB_ARRAY_ENABLED
VERTEX_ATTRIB_ARRAY_INTEGER = GLES3.GL_VERTEX_ATTRIB_ARRAY_INTEGER
VERTEX_ATTRIB_ARRAY_NORMALIZED = GLES3.GL_VERTEX_ATTRIB_ARRAY_NORMALIZED
VERTEX_ATTRIB_ARRAY_POINTER = GLES3.GL_VERTEX_ATTRIB_ARRAY_POINTER
VERTEX_ATTRIB_ARRAY_SIZE = GLES3.GL_VERTEX_ATTRIB_ARRAY_SIZE
VERTEX_ATTRIB_ARRAY_STRIDE = GLES3.GL_VERTEX_ATTRIB_ARRAY_STRIDE
VERTEX_ATTRIB_ARRAY_TYPE = GLES3.GL_VERTEX_ATTRIB_ARRAY_TYPE
VERTEX_ATTRIB_BINDING = GLES3.GL_VERTEX_ATTRIB_BINDING
VERTEX_ATTRIB_RELATIVE_OFFSET = GLES3.GL_VERTEX_ATTRIB_RELATIVE_OFFSET
VERTEX_BINDING_BUFFER = GLES3.GL_VERTEX_BINDING_BUFFER
VERTEX_BINDING_DIVISOR = GLES3.GL_VERTEX_BINDING_DIVISOR
VERTEX_BINDING_OFFSET = GLES3.GL_VERTEX_BINDING_OFFSET
VERTEX_BINDING_STRIDE = GLES3.GL_VERTEX_BINDING_STRIDE
VERTEX_SHADER = GLES3.GL_VERTEX_SHADER
VERTEX_SHADER_BIT = GLES3.GL_VERTEX_SHADER_BIT
VIEWPORT = GLES3.GL_VIEWPORT
VOID_P = GLES3.GL_VOID_P
WAIT_FAILED = GLES3.GL_WAIT_FAILED
WRITE_ONLY = GLES3.GL_WRITE_ONLY
ZERO = GLES3.GL_ZERO
bitfield = GLES3.GLbitfield
boolean = GLES3.GLboolean
byte = GLES3.GLbyte
char = GLES3.GLchar
charARB = GLES3.GLcharARB
clampd = GLES3.GLclampd
clampf = GLES3.GLclampf
clampx = GLES3.GLclampx
double = GLES3.GLdouble
double_2 = GLES3.GLdouble_2
double_3 = GLES3.GLdouble_3
double_4 = GLES3.GLdouble_4
eglImageOES = GLES3.GLeglImageOES
enum = GLES3.GLenum
fixed = GLES3.GLfixed
float = GLES3.GLfloat
float_2 = GLES3.GLfloat_2
float_3 = GLES3.GLfloat_3
float_4 = GLES3.GLfloat_4
halfARB = GLES3.GLhalfARB
halfNV = GLES3.GLhalfNV
handle = GLES3.GLhandle
handleARB = GLES3.GLhandleARB
int = GLES3.GLint
int64 = GLES3.GLint64
int64EXT = GLES3.GLint64EXT
intptr = GLES3.GLintptr
intptrARB = GLES3.GLintptrARB
short = GLES3.GLshort
sizei = GLES3.GLsizei
sizeiptr = GLES3.GLsizeiptr
sizeiptrARB = GLES3.GLsizeiptrARB
sync = GLES3.GLsync
ubyte = GLES3.GLubyte
ubyte_3 = GLES3.GLubyte_3
uint = GLES3.GLuint
uint64 = GLES3.GLuint64
uint64EXT = GLES3.GLuint64EXT
ulong = GLES3.GLulong
ushort = GLES3.GLushort
vdpauSurfaceNV = GLES3.GLvdpauSurfaceNV
void = GLES3.void
voidp = GLES3.GLvoidp
arrays = GLES3.arrays
as_8_bit = GLES3.as_8_bit
bytes = GLES3.bytes
c_int = GLES3.c_int
constant = GLES3.constant
contextdata = GLES3.contextdata
converters = GLES3.converters
ctypes = GLES3.ctypes
ctypes_version = GLES3.ctypes_version
extensions = GLES3.extensions
activeShaderProgram = GLES3.glActiveShaderProgram
activeTexture = GLES3.glActiveTexture
attachShader = GLES3.glAttachShader
beginQuery = GLES3.glBeginQuery
beginTransformFeedback = GLES3.glBeginTransformFeedback
bindAttribLocation = GLES3.glBindAttribLocation
bindBuffer = GLES3.glBindBuffer
bindBufferBase = GLES3.glBindBufferBase
bindBufferRange = GLES3.glBindBufferRange
bindFramebuffer = GLES3.glBindFramebuffer
bindImageTexture = GLES3.glBindImageTexture
bindProgramPipeline = GLES3.glBindProgramPipeline
bindRenderbuffer = GLES3.glBindRenderbuffer
bindSampler = GLES3.glBindSampler
bindTexture = GLES3.glBindTexture
bindTransformFeedback = GLES3.glBindTransformFeedback
bindVertexArray = GLES3.glBindVertexArray
bindVertexBuffer = GLES3.glBindVertexBuffer
blendColor = GLES3.glBlendColor
blendEquation = GLES3.glBlendEquation
blendEquationSeparate = GLES3.glBlendEquationSeparate
blendFunc = GLES3.glBlendFunc
blendFuncSeparate = GLES3.glBlendFuncSeparate
blitFramebuffer = GLES3.glBlitFramebuffer
bufferData = GLES3.glBufferData
bufferSubData = GLES3.glBufferSubData
checkFramebufferStatus = GLES3.glCheckFramebufferStatus
clear = GLES3.glClear
clearBufferfi = GLES3.glClearBufferfi
clearBufferfv = GLES3.glClearBufferfv
clearBufferiv = GLES3.glClearBufferiv
clearBufferuiv = GLES3.glClearBufferuiv
clearColor = GLES3.glClearColor
clearDepthf = GLES3.glClearDepthf
clearStencil = GLES3.glClearStencil
clientWaitSync = GLES3.glClientWaitSync
colorMask = GLES3.glColorMask
compileShader = GLES3.glCompileShader
compressedTexImage2D = GLES3.glCompressedTexImage2D
compressedTexImage3D = GLES3.glCompressedTexImage3D
compressedTexSubImage2D = GLES3.glCompressedTexSubImage2D
compressedTexSubImage3D = GLES3.glCompressedTexSubImage3D
copyBufferSubData = GLES3.glCopyBufferSubData
copyTexImage2D = GLES3.glCopyTexImage2D
copyTexSubImage2D = GLES3.glCopyTexSubImage2D
copyTexSubImage3D = GLES3.glCopyTexSubImage3D
createProgram = GLES3.glCreateProgram
createShader = GLES3.glCreateShader
createShaderProgramv = GLES3.glCreateShaderProgramv
cullFace = GLES3.glCullFace
deleteBuffers = GLES3.glDeleteBuffers
deleteFramebuffers = GLES3.glDeleteFramebuffers
deleteProgram = GLES3.glDeleteProgram
deleteProgramPipelines = GLES3.glDeleteProgramPipelines
deleteQueries = GLES3.glDeleteQueries
deleteRenderbuffers = GLES3.glDeleteRenderbuffers
deleteSamplers = GLES3.glDeleteSamplers
deleteShader = GLES3.glDeleteShader
deleteSync = GLES3.glDeleteSync
deleteTextures = GLES3.glDeleteTextures
deleteTransformFeedbacks = GLES3.glDeleteTransformFeedbacks
deleteVertexArrays = GLES3.glDeleteVertexArrays
depthFunc = GLES3.glDepthFunc
depthMask = GLES3.glDepthMask
depthRangef = GLES3.glDepthRangef
detachShader = GLES3.glDetachShader
disable = GLES3.glDisable
disableVertexAttribArray = GLES3.glDisableVertexAttribArray
dispatchCompute = GLES3.glDispatchCompute
dispatchComputeIndirect = GLES3.glDispatchComputeIndirect
drawArrays = GLES3.glDrawArrays
drawArraysIndirect = GLES3.glDrawArraysIndirect
drawArraysInstanced = GLES3.glDrawArraysInstanced
drawBuffers = GLES3.glDrawBuffers
drawElements = GLES3.glDrawElements
drawElementsIndirect = GLES3.glDrawElementsIndirect
drawElementsInstanced = GLES3.glDrawElementsInstanced
drawRangeElements = GLES3.glDrawRangeElements
enable = GLES3.glEnable
enableVertexAttribArray = GLES3.glEnableVertexAttribArray
endQuery = GLES3.glEndQuery
endTransformFeedback = GLES3.glEndTransformFeedback
fenceSync = GLES3.glFenceSync
finish = GLES3.glFinish
flush = GLES3.glFlush
flushMappedBufferRange = GLES3.glFlushMappedBufferRange
framebufferParameteri = GLES3.glFramebufferParameteri
framebufferRenderbuffer = GLES3.glFramebufferRenderbuffer
framebufferTexture2D = GLES3.glFramebufferTexture2D
framebufferTextureLayer = GLES3.glFramebufferTextureLayer
frontFace = GLES3.glFrontFace
genBuffers = GLES3.glGenBuffers
genFramebuffers = GLES3.glGenFramebuffers
genProgramPipelines = GLES3.glGenProgramPipelines
genQueries = GLES3.glGenQueries
genRenderbuffers = GLES3.glGenRenderbuffers
genSamplers = GLES3.glGenSamplers
genTextures = GLES3.glGenTextures
genTransformFeedbacks = GLES3.glGenTransformFeedbacks
genVertexArrays = GLES3.glGenVertexArrays
generateMipmap = GLES3.glGenerateMipmap
getActiveAttrib = GLES3.glGetActiveAttrib
getActiveUniform = GLES3.glGetActiveUniform
getActiveUniformBlockName = GLES3.glGetActiveUniformBlockName
getActiveUniformBlockiv = GLES3.glGetActiveUniformBlockiv
getActiveUniformsiv = GLES3.glGetActiveUniformsiv
getAttachedShaders = GLES3.glGetAttachedShaders
getAttribLocation = GLES3.glGetAttribLocation
getBooleani_v = GLES3.glGetBooleani_v
getBooleanv = GLES3.glGetBooleanv
getBufferParameteri64v = GLES3.glGetBufferParameteri64v
getBufferParameteriv = GLES3.glGetBufferParameteriv
getBufferPointerv = GLES3.glGetBufferPointerv
getError = GLES3.glGetError
getFloatv = GLES3.glGetFloatv
getFragDataLocation = GLES3.glGetFragDataLocation
getFramebufferAttachmentParameteriv = GLES3.glGetFramebufferAttachmentParameteriv
getFramebufferParameteriv = GLES3.glGetFramebufferParameteriv
getInteger64i_v = GLES3.glGetInteger64i_v
getInteger64v = GLES3.glGetInteger64v
getIntegeri_v = GLES3.glGetIntegeri_v
getIntegerv = GLES3.glGetIntegerv
getInternalformativ = GLES3.glGetInternalformativ
getMultisamplefv = GLES3.glGetMultisamplefv
getProgramBinary = GLES3.glGetProgramBinary
getProgramInfoLog = GLES3.glGetProgramInfoLog
getProgramInterfaceiv = GLES3.glGetProgramInterfaceiv
getProgramPipelineInfoLog = GLES3.glGetProgramPipelineInfoLog
getProgramPipelineiv = GLES3.glGetProgramPipelineiv
getProgramResourceIndex = GLES3.glGetProgramResourceIndex
getProgramResourceLocation = GLES3.glGetProgramResourceLocation
getProgramResourceName = GLES3.glGetProgramResourceName
getProgramResourceiv = GLES3.glGetProgramResourceiv
getProgramiv = GLES3.glGetProgramiv
getQueryObjectuiv = GLES3.glGetQueryObjectuiv
getQueryiv = GLES3.glGetQueryiv
getRenderbufferParameteriv = GLES3.glGetRenderbufferParameteriv
getSamplerParameterfv = GLES3.glGetSamplerParameterfv
getSamplerParameteriv = GLES3.glGetSamplerParameteriv
getShaderInfoLog = GLES3.glGetShaderInfoLog
getShaderPrecisionFormat = GLES3.glGetShaderPrecisionFormat
getShaderSource = GLES3.glGetShaderSource
getShaderiv = GLES3.glGetShaderiv
getString = GLES3.glGetString
getStringi = GLES3.glGetStringi
getSynciv = GLES3.glGetSynciv
getTexLevelParameterfv = GLES3.glGetTexLevelParameterfv
getTexLevelParameteriv = GLES3.glGetTexLevelParameteriv
getTexParameterfv = GLES3.glGetTexParameterfv
getTexParameteriv = GLES3.glGetTexParameteriv
getTransformFeedbackVarying = GLES3.glGetTransformFeedbackVarying
getUniformBlockIndex = GLES3.glGetUniformBlockIndex
getUniformIndices = GLES3.glGetUniformIndices
getUniformLocation = GLES3.glGetUniformLocation
getUniformfv = GLES3.glGetUniformfv
getUniformiv = GLES3.glGetUniformiv
getUniformuiv = GLES3.glGetUniformuiv
getVertexAttribIiv = GLES3.glGetVertexAttribIiv
getVertexAttribIuiv = GLES3.glGetVertexAttribIuiv
getVertexAttribPointerv = GLES3.glGetVertexAttribPointerv
getVertexAttribfv = GLES3.glGetVertexAttribfv
getVertexAttribiv = GLES3.glGetVertexAttribiv
hint = GLES3.glHint
initGles220VERSION = GLES3.glInitGles220VERSION
initGles330VERSION = GLES3.glInitGles330VERSION
initGles331VERSION = GLES3.glInitGles331VERSION
invalidateFramebuffer = GLES3.glInvalidateFramebuffer
invalidateSubFramebuffer = GLES3.glInvalidateSubFramebuffer
isBuffer = GLES3.glIsBuffer
isEnabled = GLES3.glIsEnabled
isFramebuffer = GLES3.glIsFramebuffer
isProgram = GLES3.glIsProgram
isProgramPipeline = GLES3.glIsProgramPipeline
isQuery = GLES3.glIsQuery
isRenderbuffer = GLES3.glIsRenderbuffer
isSampler = GLES3.glIsSampler
isShader = GLES3.glIsShader
isSync = GLES3.glIsSync
isTexture = GLES3.glIsTexture
isTransformFeedback = GLES3.glIsTransformFeedback
isVertexArray = GLES3.glIsVertexArray
lineWidth = GLES3.glLineWidth
linkProgram = GLES3.glLinkProgram
mapBufferRange = GLES3.glMapBufferRange
memoryBarrier = GLES3.glMemoryBarrier
memoryBarrierByRegion = GLES3.glMemoryBarrierByRegion
pauseTransformFeedback = GLES3.glPauseTransformFeedback
pixelStorei = GLES3.glPixelStorei
polygonOffset = GLES3.glPolygonOffset
programBinary = GLES3.glProgramBinary
programParameteri = GLES3.glProgramParameteri
programUniform1f = GLES3.glProgramUniform1f
programUniform1fv = GLES3.glProgramUniform1fv
programUniform1i = GLES3.glProgramUniform1i
programUniform1iv = GLES3.glProgramUniform1iv
programUniform1ui = GLES3.glProgramUniform1ui
programUniform1uiv = GLES3.glProgramUniform1uiv
programUniform2f = GLES3.glProgramUniform2f
programUniform2fv = GLES3.glProgramUniform2fv
programUniform2i = GLES3.glProgramUniform2i
programUniform2iv = GLES3.glProgramUniform2iv
programUniform2ui = GLES3.glProgramUniform2ui
programUniform2uiv = GLES3.glProgramUniform2uiv
programUniform3f = GLES3.glProgramUniform3f
programUniform3fv = GLES3.glProgramUniform3fv
programUniform3i = GLES3.glProgramUniform3i
programUniform3iv = GLES3.glProgramUniform3iv
programUniform3ui = GLES3.glProgramUniform3ui
programUniform3uiv = GLES3.glProgramUniform3uiv
programUniform4f = GLES3.glProgramUniform4f
programUniform4fv = GLES3.glProgramUniform4fv
programUniform4i = GLES3.glProgramUniform4i
programUniform4iv = GLES3.glProgramUniform4iv
programUniform4ui = GLES3.glProgramUniform4ui
programUniform4uiv = GLES3.glProgramUniform4uiv
programUniformMatrix2fv = GLES3.glProgramUniformMatrix2fv
programUniformMatrix2x3fv = GLES3.glProgramUniformMatrix2x3fv
programUniformMatrix2x4fv = GLES3.glProgramUniformMatrix2x4fv
programUniformMatrix3fv = GLES3.glProgramUniformMatrix3fv
programUniformMatrix3x2fv = GLES3.glProgramUniformMatrix3x2fv
programUniformMatrix3x4fv = GLES3.glProgramUniformMatrix3x4fv
programUniformMatrix4fv = GLES3.glProgramUniformMatrix4fv
programUniformMatrix4x2fv = GLES3.glProgramUniformMatrix4x2fv
programUniformMatrix4x3fv = GLES3.glProgramUniformMatrix4x3fv
readBuffer = GLES3.glReadBuffer
readPixels = GLES3.glReadPixels
releaseShaderCompiler = GLES3.glReleaseShaderCompiler
renderbufferStorage = GLES3.glRenderbufferStorage
renderbufferStorageMultisample = GLES3.glRenderbufferStorageMultisample
resumeTransformFeedback = GLES3.glResumeTransformFeedback
sampleCoverage = GLES3.glSampleCoverage
sampleMaski = GLES3.glSampleMaski
samplerParameterf = GLES3.glSamplerParameterf
samplerParameterfv = GLES3.glSamplerParameterfv
samplerParameteri = GLES3.glSamplerParameteri
samplerParameteriv = GLES3.glSamplerParameteriv
scissor = GLES3.glScissor
shaderBinary = GLES3.glShaderBinary
shaderSource = GLES3.glShaderSource
stencilFunc = GLES3.glStencilFunc
stencilFuncSeparate = GLES3.glStencilFuncSeparate
stencilMask = GLES3.glStencilMask
stencilMaskSeparate = GLES3.glStencilMaskSeparate
stencilOp = GLES3.glStencilOp
stencilOpSeparate = GLES3.glStencilOpSeparate
texImage2D = GLES3.glTexImage2D
texImage3D = GLES3.glTexImage3D
texParameterf = GLES3.glTexParameterf
texParameterfv = GLES3.glTexParameterfv
texParameteri = GLES3.glTexParameteri
texParameteriv = GLES3.glTexParameteriv
texStorage2D = GLES3.glTexStorage2D
texStorage2DMultisample = GLES3.glTexStorage2DMultisample
texStorage3D = GLES3.glTexStorage3D
texSubImage2D = GLES3.glTexSubImage2D
texSubImage3D = GLES3.glTexSubImage3D
transformFeedbackVaryings = GLES3.glTransformFeedbackVaryings
uniform1f = GLES3.glUniform1f
uniform1fv = GLES3.glUniform1fv
uniform1i = GLES3.glUniform1i
uniform1iv = GLES3.glUniform1iv
uniform1ui = GLES3.glUniform1ui
uniform1uiv = GLES3.glUniform1uiv
uniform2f = GLES3.glUniform2f
uniform2fv = GLES3.glUniform2fv
uniform2i = GLES3.glUniform2i
uniform2iv = GLES3.glUniform2iv
uniform2ui = GLES3.glUniform2ui
uniform2uiv = GLES3.glUniform2uiv
uniform3f = GLES3.glUniform3f
uniform3fv = GLES3.glUniform3fv
uniform3i = GLES3.glUniform3i
uniform3iv = GLES3.glUniform3iv
uniform3ui = GLES3.glUniform3ui
uniform3uiv = GLES3.glUniform3uiv
uniform4f = GLES3.glUniform4f
uniform4fv = GLES3.glUniform4fv
uniform4i = GLES3.glUniform4i
uniform4iv = GLES3.glUniform4iv
uniform4ui = GLES3.glUniform4ui
uniform4uiv = GLES3.glUniform4uiv
uniformBlockBinding = GLES3.glUniformBlockBinding
uniformMatrix2fv = GLES3.glUniformMatrix2fv
uniformMatrix2x3fv = GLES3.glUniformMatrix2x3fv
uniformMatrix2x4fv = GLES3.glUniformMatrix2x4fv
uniformMatrix3fv = GLES3.glUniformMatrix3fv
uniformMatrix3x2fv = GLES3.glUniformMatrix3x2fv
uniformMatrix3x4fv = GLES3.glUniformMatrix3x4fv
uniformMatrix4fv = GLES3.glUniformMatrix4fv
uniformMatrix4x2fv = GLES3.glUniformMatrix4x2fv
uniformMatrix4x3fv = GLES3.glUniformMatrix4x3fv
unmapBuffer = GLES3.glUnmapBuffer
useProgram = GLES3.glUseProgram
useProgramStages = GLES3.glUseProgramStages
validateProgram = GLES3.glValidateProgram
validateProgramPipeline = GLES3.glValidateProgramPipeline
vertexAttrib1f = GLES3.glVertexAttrib1f
vertexAttrib1fv = GLES3.glVertexAttrib1fv
vertexAttrib2f = GLES3.glVertexAttrib2f
vertexAttrib2fv = GLES3.glVertexAttrib2fv
vertexAttrib3f = GLES3.glVertexAttrib3f
vertexAttrib3fv = GLES3.glVertexAttrib3fv
vertexAttrib4f = GLES3.glVertexAttrib4f
vertexAttrib4fv = GLES3.glVertexAttrib4fv
vertexAttribBinding = GLES3.glVertexAttribBinding
vertexAttribDivisor = GLES3.glVertexAttribDivisor
vertexAttribFormat = GLES3.glVertexAttribFormat
vertexAttribI4i = GLES3.glVertexAttribI4i
vertexAttribI4iv = GLES3.glVertexAttribI4iv
vertexAttribI4ui = GLES3.glVertexAttribI4ui
vertexAttribI4uiv = GLES3.glVertexAttribI4uiv
vertexAttribIFormat = GLES3.glVertexAttribIFormat
vertexAttribIPointer = GLES3.glVertexAttribIPointer
vertexAttribPointer = GLES3.glVertexAttribPointer
vertexBindingDivisor = GLES3.glVertexBindingDivisor
viewport = GLES3.glViewport
waitSync = GLES3.glWaitSync
int32_t = GLES3.int32_t
int64_t = GLES3.int64_t
long = GLES3.long
platform = GLES3.platform
size_t = GLES3.size_t
sizeof = GLES3.sizeof
unicode = GLES3.unicode
wrapper = GLES3.wrapper
